### ISSUE TITLE
SIGILL, Illegal instruction from libkernellibs.so

### ISSUE THREAD

**Issue by aamir-s18** [intel/intel-extension-for-transformers#1063]
Hey, I am trying to run [bert-mini-sst2-distilled-sparse-90-1X4-block](https://huggingface.co/Intel/bert-mini-sst2-distilled-sparse-90-1X4-block) with Neural IR like this:

```python
import numpy as np

from intel_extension_for_transformers.llm.runtime.deprecated.compile.graph import Graph
from transformers import AutoTokenizer

graph = Graph()
graph.graph_init("sparse_int8_ir/conf.yaml", "sparse_int8_ir/model.bin")

tokenizer = AutoTokenizer.from_pretrained("bert-mini-sst2-distilled-sparse-90-1X4-block")

t = tokenizer(["hey"])
input_ids_data = t['input_ids']
segment_ids_data =t['token_type_ids']
input_mask_data = t['attention_mask']
sample_size = len(input_ids_data) if isinstance(input_ids_data, list) else 1
model_input = [np.array(input_ids_data).reshape(sample_size, -1).astype('int32'), np.array(segment_ids_data).reshape(sample_size, -1).astype('int32'), np.array(input_mask_data).reshape(sample_size, -1).astype('int32')]

graph.inference(inp)
```

Running this code I am getting Illegal instruction (core dumped). After digging deeper with gdb I am getting this log trace:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3f6a700 (LWP 102827)]
[New Thread 0x7ffff3769700 (LWP 102828)]
[New Thread 0x7ffff0f68700 (LWP 102829)]
[New Thread 0x7fffee767700 (LWP 102830)]
[New Thread 0x7fffebf66700 (LWP 102831)]
[New Thread 0x7fffe5264700 (LWP 102857)]
[New Thread 0x7fffe5063700 (LWP 102858)]
[New Thread 0x7fffdc8b5700 (LWP 102859)]
[New Thread 0x7fffe48b5700 (LWP 102860)]
[New Thread 0x7fffe46b4700 (LWP 102862)]
[New Thread 0x7fffe44b3700 (LWP 102863)]
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 1 "python" received signal SIGILL, Illegal instruction.
0x00007fffdce1959f in jd::jit_generator::jit_generator(unsigned long, void*) () from /home/ubuntu/.venv/lib/python3.11/site-packages/intel_extension_for_transformers/libkernellibs.so
```

It would be great if you could help here.

**Comment by aamir-s18** [comment]
Okay I build it with with `CMAKE_BUILD_TYPE=Debug pip install -ve .`. And got the following: 

`F20231221 21:01:42.529968 172169 isa.hpp:55] Only support device with Intel AVX-512!`. My current environment has a AMD CPU with AVX and AVX2. So it means, you just support Intel CPUs for the IR?

**Comment by a32543254** [comment]
Yes, for this bert sparse example, we require your machine at less have AVX-512 isa to run sparse kernel .

**Comment by aamir-s18** [comment]
Thank you. Is it required for all bert sparse models? Also do you plan to fix the ToDos in the kernels?

**Comment by airMeng** [comment]
> Thank you. Is it required for all bert sparse models? It would be great to know, when what works.
> 
> Also do you plan to fix the ToDos in the kernels?

yes, we only implemented avx512 kernels for structural sparsity.
we will turn to unstructured sparsity in LLM, so we will not keep updating unstructural kernels. But we are welcome for PRs from community to fix potential issues.

**Comment by aamir-s18** [comment]
Thank you! I will look into it :)
