### ISSUE TITLE
Features request llama.cpp statistics for llama2  models

### ISSUE THREAD

**Issue by RachelShalom** [intel/intel-extension-for-transformers#1091]
Hi is there an option to add inference time statistics in the output of the llama2 models? when using llama.cpp with llama2 model you get statistics output like the following:
![image](https://github.com/intel/intel-extension-for-transformers/assets/24391976/005799e1-0276-42c3-9f0f-c239fb90d4c0)

**Comment by zhenwei-intel** [comment]
Hi @RachelShalom ,

we are working on it, please refer this pr: https://github.com/intel/intel-extension-for-transformers/pull/1054

**Comment by zhenwei-intel** [comment]
pr is merged, close this issue
