### ISSUE TITLE
whisper.cpp

### ISSUE THREAD

**Issue by dyt06** [intel/intel-extension-for-transformers#1094]
C:\Windows\system32>D:\o\1\run_whisper.exe -l zh -m D:\o\1\1.bin -f D:\o\1\1.wav -osrt
whisper_init_from_file_no_state: loading model from 'D:\o\1\1.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 8
whisper_model_load: qntvr         = 1
whisper_model_load: type          = 4
whisper_model_load: mem required  =  951.00 MB (+   43.00 MB per decoder)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     =  514.11 MB
AVX:1 AVX2:1 AVX512F:0 AVX_VNNI:0 AVX512_VNNI:0 AMX_INT8:0 AMX_BF16:0 AVX512_BF16:0 AVX512_FP16:0
NE_ASSERT: E:\intel\intel_extension_for_transformers\llm\runtime\graph\core\ne_layers.c:803: ((uintptr_t)(ctx->mem_buffer)) % NE_MEM_ALIGN == 0

**Comment by a32543254** [comment]
could you use this branch to run whisper ? 
Same issue we already fix it in this pr.
https://github.com/intel/intel-extension-for-transformers/pull/809

**Comment by dyt06** [comment]
What can I do to gain the ability to run Whisper?

> 你能用这个分支来运行whisper吗？同样的问题我们已经在这个公关中修复了它。 #809

What can I do to gain the ability to run Whisper?

**Comment by DDEle** [comment]
请基于分支 `whisper_opt` 编译和运行。（另外，有点好奇您是如何获得日志中的 `run_whisper.exe` 可执行文件的？我看似乎根据主分支上的文档并没有介绍它的使用？）

**Comment by dyt06** [comment]
> 请基于分支 `whisper_opt` 编译和运行。（另外，有点好奇您是如何获得日志中的 `run_whisper.exe` 可执行文件的？我看似乎根据主分支上的文档并没有介绍它的使用？）

C:\Windows\system32>D:\o\1\run_whisper.exe -l zh -m D:\o\1\1.bin -f D:\o\1\1.wav -osrt
whisper_init_from_file_no_state: loading model from 'D:\o\1\1.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 8
whisper_model_load: qntvr         = 1
whisper_model_load: type          = 4
whisper_model_load: mem required  =  951.00 MB (+   43.00 MB per decoder)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     =  514.11 MB
AVX:1 AVX2:1 AVX512F:0 AVX_VNNI:0 AVX512_VNNI:0 AMX_INT8:0 AMX_BF16:0 AVX512_BF16:0 AVX512_FP16:0
NE_ASSERT: E:\intel\intel_extension_for_transformers\llm\runtime\graph\core\ne_layers.c:803: ((uintptr_t)(ctx->mem_buffer)) % NE_MEM_ALIGN == 0

C:\Windows\system32>D:\o\1\run_whisper.exe -l zh -m D:\o\1\2.bin -f D:\o\1\1.wav -osrt
whisper_init_from_file_no_state: loading model from 'D:\o\1\2.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1280
whisper_model_load: n_audio_head  = 20
whisper_model_load: n_audio_layer = 32
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1280
whisper_model_load: n_text_head   = 20
whisper_model_load: n_text_layer  = 32
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 8
whisper_model_load: qntvr         = 1
whisper_model_load: type          = 5
whisper_model_load: mem required  = 1639.00 MB (+   71.00 MB per decoder)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     = 1030.68 MB
AVX:1 AVX2:1 AVX512F:0 AVX_VNNI:0 AVX512_VNNI:0 AMX_INT8:0 AMX_BF16:0 AVX512_BF16:0 AVX512_FP16:0
NE_ASSERT: E:\intel\intel_extension_for_transformers\llm\runtime\graph\core\ne_layers.c:803: ((uintptr_t)(ctx->mem_buffer)) % NE_MEM_ALIGN == 0

这是从分支 `whisper_opt下载后编译的效果。

**Comment by dyt06** [comment]
经多次尝试后，发现是chcp(936)的问题。现在可以运行了。但，它太慢了，比whisper.cpp(1.52)还慢。

output_srt: saving output to 'D:\o\1\1.wav.srt'

whisper_print_timings:     load time =  1947.19 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =   612.70 ms
whisper_print_timings:   sample time =   217.38 ms /   262 runs (    0.83 ms per run)
whisper_print_timings:   encode time = 154694.25 ms /     3 runs (51564.75 ms per run)
whisper_print_timings:   decode time = 22602.74 ms /   262 runs (   86.27 ms per run)
whisper_print_timings:    total time = 180118.12 ms

这是whisper.cpp(1.52)的效果：

[00:00:54.000 --> 00:00:57.000]  迅速关闭煤气源和电源
[00:00:57.000 --> 00:01:00.000]  打开窗户通风换气,降低温度。

output_srt: saving output to 'D:\o\1\1.wav.srt'

whisper_print_timings:     load time =   383.82 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =   116.32 ms
whisper_print_timings:   sample time =  1132.29 ms /  1323 runs (    0.86 ms per run)
whisper_print_timings:   encode time = 26101.40 ms /     3 runs ( 8700.47 ms per run)
whisper_print_timings:   decode time =    72.99 ms /     3 runs (   24.33 ms per run)
whisper_print_timings:   batchd time = 19166.94 ms /  1311 runs (   14.62 ms per run)
whisper_print_timings:   prompt time =  1248.19 ms /   105 runs (   11.89 ms per run)
whisper_print_timings:    total time = 48237.80 ms

**Comment by intellinjun** [comment]
1. ITREX result on clx
llm/runtime/graph$ ./build/bin/run_whisper  -m whisper_q40.bin  -f ./whisper.cpp/samples/jfk.wav 
whisper_init_from_file_no_state: loading model from 'whisper_q40.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 384
whisper_model_load: n_audio_head  = 6
whisper_model_load: n_audio_layer = 4
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 384
whisper_model_load: n_text_head   = 6
whisper_model_load: n_text_layer  = 4
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 2
whisper_model_load: qntvr         = 2
whisper_model_load: type          = 1
whisper_model_load: mem required  =  153.00 MB (+    3.00 MB per decoder)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: model ctx     =   23.68 MB
AVX:1 AVX2:1 AVX512F:1 AVX_VNNI:0 AVX512_VNNI:1 AMX_INT8:0 AMX_BF16:0 AVX512_BF16:0 AVX512_FP16:0
whisper_model_load: model size    =   23.59 MB
whisper_init_state: kv self size  =    2.62 MB
whisper_init_state: kv cross size =    8.79 MB

system_info: n_threads = 4 / 112 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | F16C = 1 | SSE3 = 1 | VSX = 0 | 

main: processing './whisper.cpp/samples/jfk.wav' (176000 samples, 11.0 sec), 4 threads, 1 processors, lang = en, task = transcribe, timestamps = 1 ...


[00:00:00.000 --> 00:00:02.000]   And so my fellow Americans
[00:00:02.000 --> 00:00:05.200]   ask not
[00:00:05.200 --> 00:00:07.200]   What your country can do for you
[00:00:07.200 --> 00:00:10.160]   ask what you can do for your country


whisper_print_timings:     load time =    65.66 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =   101.46 ms
whisper_print_timings:   sample time =    17.03 ms /    30 runs (    0.57 ms per run)
whisper_print_timings:   encode time =   652.55 ms /     1 runs (  652.55 ms per run)
whisper_print_timings:   decode time =   109.07 ms /    30 runs (    3.64 ms per run)
whisper_print_timings:    total time =   990.63 ms

2. whisper_cpp on clx
whisper.cpp$ ./main  -m whisper_q40.bin  -f samples/jfk.wav 
whisper_init_from_file_with_params_no_state: loading model from 'whisper_q40.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 384
whisper_model_load: n_audio_head  = 6
whisper_model_load: n_audio_layer = 4
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 384
whisper_model_load: n_text_head   = 6
whisper_model_load: n_text_layer  = 4
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 2
whisper_model_load: qntvr         = 2
whisper_model_load: type          = 1 (tiny)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      CPU buffer size =    24.81 MB
whisper_model_load: model size    =   24.74 MB
whisper_init_state: kv self size  =    8.26 MB
whisper_init_state: kv cross size =    9.22 MB
whisper_init_state: compute buffer (conv)   =   12.17 MB
whisper_init_state: compute buffer (encode) =   64.92 MB
whisper_init_state: compute buffer (cross)  =    4.01 MB
whisper_init_state: compute buffer (decode) =   96.02 MB

system_info: n_threads = 4 / 112 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0 | 

main: processing 'samples/jfk.wav' (176000 samples, 11.0 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...


[00:00:00.000 --> 00:00:03.020]   And so my fellow Americans
[00:00:03.020 --> 00:00:05.000]   asked not
[00:00:05.000 --> 00:00:08.000]   "What your country can do for you?"
[00:00:08.000 --> 00:00:12.000]   asked "What you can do for your country?"


whisper_print_timings:     load time =    68.88 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =    33.28 ms
whisper_print_timings:   sample time =   126.78 ms /   162 runs (    0.78 ms per run)
whisper_print_timings:   encode time =   682.78 ms /     1 runs (  682.78 ms per run)
whisper_print_timings:   decode time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:   batchd time =   494.45 ms /   160 runs (    3.09 ms per run)
whisper_print_timings:   prompt time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:    total time =  1413.45 ms

**Comment by intellinjun** [comment]
@dyt06 I used Whisper Tiny on the clx machine, I found that ITREX is faster than whisper.cpp, what machine are you using?
