### ISSUE TITLE
AssertionError: Fail to convert pytorch model! Can't use any 6,7 billion transformer model like llama2,chatgml with intel-extension-for-transformers! i'm getting this error!

### ISSUE THREAD

**Issue by dahwin** [intel/intel-extension-for-transformers#1099]
`from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig

model_name = "meta-llama/Llama-2-7b-chat-hf"
woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4")
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
streamer = TextStreamer(tokenizer)
model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, trust_remote_code=True)`

`
Loading model file meta-llama/Llama-2-7b-chat-hf
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py", line 1325, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py", line 1305, in main
    model_plus = load_some_model(args.model)
  File "/opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py", line 1217, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py", line 980, in lazy_load_file
    fp = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'meta-llama/Llama-2-7b-chat-hf'
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[2], line 9
      7 tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
      8 streamer = TextStreamer(tokenizer)
----> 9 model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, trust_remote_code=True)

File /opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/transformers/modeling/modeling_auto.py:173, in _BaseQBitsAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    170     from intel_extension_for_transformers.llm.runtime.graph import Model
    172     model = Model()
--> 173     model.init(
    174         pretrained_model_name_or_path,
    175         weight_dtype=quantization_config.weight_dtype,
    176         alg=quantization_config.scheme,
    177         group_size=quantization_config.group_size,
    178         scale_dtype=quantization_config.scale_dtype,
    179         compute_dtype=quantization_config.compute_dtype,
    180         use_ggml=quantization_config.use_ggml,
    181         use_quant=quantization_config.use_quant,
    182         use_gptq=quantization_config.use_gptq,
    183     )
    184     return model
    185 else:

File /opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/__init__.py:118, in Model.init(self, model_name, use_quant, use_gptq, **quant_kwargs)
    116 if not os.path.exists(fp32_bin):
    117     convert_model(model_name, fp32_bin, "f32")
--> 118     assert os.path.exists(fp32_bin), "Fail to convert pytorch model"
    120 if not use_quant:
    121     print("FP32 model will be used.")

AssertionError: Fail to convert pytorch model`

**Comment by DDEle** [comment]
> Seems that the model must be pre-downloaded as local files. Please clone the model repo from HF
> -- https://github.com/intel/intel-extension-for-transformers/discussions/1081#discussioncomment-7969153

We have noticed the problem that (some) models can only be loaded from the local path but failed when trying to fetch from huggingface. The problem will probably fixed soon after the new year holidays. Before that, you can manually download/clone from hunggingface and replace `model_name` with your local model.

**Comment by VincyZhang** [comment]
Hi @dahwin, is there any update using local model? If there is no more questions, we will close this issue.

**Comment by dahwin** [comment]
I have check Please wait for today

**Comment by dahwin** [comment]
### I have download the model in local dir!
### See
'''
import os

folder_path = '/kaggle/working/THUDM/chatglm3-6b'
files = os.listdir(folder_path)

for file in files:
    print(file)
pytorch_model-00001-of-00007.bin
configuration_chatglm.py
.gitattributes
tokenizer.model
config.json
tokenization_chatglm.py
pytorch_model.bin.index.json
pytorch_model-00003-of-00007.bin
modeling_chatglm.py
pytorch_model-00006-of-00007.bin
pytorch_model-00005-of-00007.bin
README.md
pytorch_model-00007-of-00007.bin
MODEL_LICENSE
pytorch_model-00004-of-00007.bin
pytorch_model-00002-of-00007.bin
model.safetensors.index.json
tokenizer_config.json
quantization.py
'''


#But still i can't load the model

'''
from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig

model_name = '/kaggle/working/THUDM/chatglm3-6b'
woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4")
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True, local_files_only=True)
streamer = TextStreamer(tokenizer)
model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, trust_remote_code=True)`

# error
`from .autonotebook import tqdm as notebook_tqdm
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[2], line 6
      4 model_name = '/kaggle/working/THUDM/chatglm3-6b'
      5 woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4")
----> 6 tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True, local_files_only=True)
      7 streamer = TextStreamer(tokenizer)
      8 model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, trust_remote_code=True)

File /usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py:716, in AutoTokenizer.from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    714 if config_tokenizer_class is None:
    715     if not isinstance(config, PretrainedConfig):
--> 716         config = AutoConfig.from_pretrained(
    717             pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
    718         )
    719     config_tokenizer_class = config.tokenizer_class
    720     if hasattr(config, "auto_map") and "AutoTokenizer" in config.auto_map:

File /usr/local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1034, in AutoConfig.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   1031 trust_remote_code = kwargs.pop("trust_remote_code", None)
   1032 code_revision = kwargs.pop("code_revision", None)
-> 1034 config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
   1035 has_remote_code = "auto_map" in config_dict and "AutoConfig" in config_dict["auto_map"]
   1036 has_local_code = "model_type" in config_dict and config_dict["model_type"] in CONFIG_MAPPING

File /usr/local/lib/python3.10/site-packages/transformers/configuration_utils.py:620, in PretrainedConfig.get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    618 original_kwargs = copy.deepcopy(kwargs)
    619 # Get config dict associated with the base config file
--> 620 config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
    621 if "_commit_hash" in config_dict:
    622     original_kwargs["_commit_hash"] = config_dict["_commit_hash"]

File /usr/local/lib/python3.10/site-packages/transformers/configuration_utils.py:675, in PretrainedConfig._get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    671 configuration_file = kwargs.pop("_configuration_file", CONFIG_NAME)
    673 try:
    674     # Load from local folder or from cache or download from model Hub and cache
--> 675     resolved_config_file = cached_file(
    676         pretrained_model_name_or_path,
    677         configuration_file,
    678         cache_dir=cache_dir,
    679         force_download=force_download,
    680         proxies=proxies,
    681         resume_download=resume_download,
    682         local_files_only=local_files_only,
    683         token=token,
    684         user_agent=user_agent,
    685         revision=revision,
    686         subfolder=subfolder,
    687         _commit_hash=commit_hash,
    688     )
    689     commit_hash = extract_commit_hash(resolved_config_file, commit_hash)
    690 except EnvironmentError:
    691     # Raise any environment error raise by `cached_file`. It will have a helpful error message adapted to
    692     # the original exception.

File /usr/local/lib/python3.10/site-packages/transformers/utils/hub.py:400, in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)
    398 if not os.path.isfile(resolved_file):
    399     if _raise_exceptions_for_missing_entries:
--> 400         raise EnvironmentError(
    401             f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
    402             f"'[https://huggingface.co/](https://huggingface.co/%3C/span%3E%3Cspan) class="ansi-bold" style="color:rgb(175,95,135)">{path_or_repo_id}/{revision}' for available files."
    403         )
    404     else:
    405         return None

OSError: /kaggle/working/THUDM/chatglm3-6b does not appear to have a file named config.json. Checkout 'https://huggingface.co//kaggle/working/THUDM/chatglm3-6b/None' for available files
'''





# please solve this issue

**Comment by a32543254** [comment]
Please see your log here:

OSError: /kaggle/working/THUDM/chatglm3-6b does not appear to have a file named config.json.  Checkout 'https://huggingface.co//kaggle/working/THUDM/chatglm3-6b/None' for available files

could you  make sure whether the config.json is in corrext path.

**Comment by dahwin** [comment]
> Please see your log here:
> 
> OSError: /kaggle/working/THUDM/chatglm3-6b does not appear to have a file named config.json. Checkout 'https://huggingface.co//kaggle/working/THUDM/chatglm3-6b/None' for available files
> 
> could you make sure whether the config.json is in corrext path.

this is a path :  /kaggle/working/THUDM/chatglm3-6b
where i have download the model !
not a huggingface model!
one contributor priviously told me to download the model !
then put the model dir path in my transformers library model

**Comment by dahwin** [comment]
> `from transformers import AutoTokenizer, TextStreamer from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig
> 
> model_name = "meta-llama/Llama-2-7b-chat-hf" woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4") tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True) streamer = TextStreamer(tokenizer) model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, trust_remote_code=True)`
> 
> ## `
> Loading model file meta-llama/Llama-2-7b-chat-hf
> Traceback (most recent call last):
> File "/opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py", line 1325, in
> main()
> File "/opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py", line 1305, in main
> model_plus = load_some_model(args.model)
> File "/opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py", line 1217, in load_some_model
> models_plus.append(lazy_load_file(path))
> File "/opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py", line 980, in lazy_load_file
> fp = open(path, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'meta-llama/Llama-2-7b-chat-hf'
> AssertionError Traceback (most recent call last) Cell In[2], line 9 7 tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True) 8 streamer = TextStreamer(tokenizer) ----> 9 model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, trust_remote_code=True)
> 
> File /opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/transformers/modeling/modeling_auto.py:173, in _BaseQBitsAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs) 170 from intel_extension_for_transformers.llm.runtime.graph import Model 172 model = Model() --> 173 model.init( 174 pretrained_model_name_or_path, 175 weight_dtype=quantization_config.weight_dtype, 176 alg=quantization_config.scheme, 177 group_size=quantization_config.group_size, 178 scale_dtype=quantization_config.scale_dtype, 179 compute_dtype=quantization_config.compute_dtype, 180 use_ggml=quantization_config.use_ggml, 181 use_quant=quantization_config.use_quant, 182 use_gptq=quantization_config.use_gptq, 183 ) 184 return model 185 else:
> 
> File /opt/conda/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/**init**.py:118, in Model.init(self, model_name, use_quant, use_gptq, **quant_kwargs) 116 if not os.path.exists(fp32_bin): 117 convert_model(model_name, fp32_bin, "f32") --> 118 assert os.path.exists(fp32_bin), "Fail to convert pytorch model" 120 if not use_quant: 121 print("FP32 model will be used.")
> 
> AssertionError: Fail to convert pytorch model`

I have got this error 
when i have put the hf model id

**Comment by a32543254** [comment]
firstly, for llama2 model you need download model to local path
secondly, we don't support chatglm3 yet.
could you try llama2 download to local path 
or try use model id for chatglm v1 / v2

**Comment by dahwin** [comment]
> firstly, for llama2 model you need download model to local path
> secondly, we don't support chatglm3 yet.
> could you try llama2 download to local path 
> or try use model id for chatglm v1 / v2  

Ok I'll try it now!

Then I will tell you

**Comment by dahwin** [comment]
it worked
