### ISSUE TITLE
BF16 Inference 

### ISSUE THREAD

**Issue by ailxcds** [intel/intel-extension-for-transformers#1115]
Is there a way to run the model as weight dtype bf16 without any quantization, similar to transformers in this way:
```python
AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.bfloat16)
```

or like llama.cpp:
./main -m ./models/ggml-model-f16.gguf -n 128

**Comment by zhenwei-intel** [comment]
hi @ailxcds,

Currently, we do not support the weight dtype of BF16. Please refer to this document for the supported matrices.

https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/llm/runtime/graph#supported-matrix-multiplication-data-types-combinations
