### ISSUE TITLE
[LLM Runtime] OOM when running Llama2-70B, but not having this issue with llama.cpp 

### ISSUE THREAD

**Issue by aahouzi** [intel/intel-extension-for-transformers#1136]
### Current Behavior:

- Doing a benchmark between **llama.cpp** and **LLM Runtime** to compare the speed-up I get. When running the llama2-70B model in ggml format int8 precision (weights + computation), with llama.cpp the model works fine, and take about 56% of my memory @2.43 tokens/sec. However, when I take the int8 ggml file to run it with LLM Runtime code, I get an OOM after getting stuck here:

![Screenshot 2024-01-11 173222](https://github.com/intel/intel-extension-for-transformers/assets/112881240/9015a8a1-47f0-4227-b2fd-ecbf782b73f6)

### Expected Behavior:
- Naturally, I expect the int8 ggml file to work for LLM Runtime as well, and not have the OOM issue, since it worked with llama.cpp

- In the documentation, u say that we can run the LLM Runtime with ggml format, so I don't even need to convert the model using your scripts. **Am I right or I need to re-do the conversion + quantization starting from the HF model ?**

### Steps To Reproduce:

- For **llama.cpp**, I just followed the instructions in the official documentation, and I run the following commands:

```
python convert.py <model-path> # to F16
quantize.exe ggml-model-q8_0.bin q8_0
main.exe -m ggml-model-q8_0.bin -p "Building a website can be done in 10 simple steps:" -n 512 -gqa 8 --no-mmap --ignore-eos
```

- For **LLM Runtime**, I took the int8 ggml file obtained before, and run it directly with the inference script:

```
python scripts/inference.py --model_name llama2 -m ggml-model-q8_0.bin -n 512 -p "Building a website can be done in 10 simple steps:"
```

### Environment:

- **OS:** Windows 11
- **HW:** SPR w9-3595X E5 128GB

**Comment by a32543254** [comment]
Hi [aahouzi](https://github.com/aahouzi)
You can’t feed ggml bin to our framework directly.
we can only support the bin file generated by us, we have our format of bin. 

In the feature we will support GGUF format model, at that feature, you can use llama.cpp gguf as well.

Regards,
Bo

**Comment by Zhenzhong1** [comment]
Hi @aahouzi 

Two tips~~
Please re-do the conversion + quantization q4_0 to check the pipeline on your machine.

Please use the  `--model_name llama` rather than `llama2` when inference, but it works for llama & llama2. Llama & Llama2 have the same model structure, here we only accept the 'llama'.

**Comment by aahouzi** [comment]
I tried doing the conversion with your scripts, and now it's working. Thanks for ur help !
