### ISSUE TITLE
When I loaded my quantized low-bit model, I encountered the following issue: like that"size mismatch for transformer.h.0.attn.c_attn.weight: copying a parameter with shape torch.Size([31457536]) from the checkpoint, whereas the shape in the current model is torch.Size([12288, 4096])."

### ISSUE THREAD

**Issue by WCSY-YG** [intel/intel-extension-for-transformers#1172]
I have quantized a model using weight-only quantization and saved it locally, however, I encountered an error while trying to load the local model. What should I do in this situation?
![Uploading 1.png…]()

**Comment by WCSY-YG** [comment]
![Uploading 1.png…]()

**Comment by kevinintel** [comment]
can't open the image
May you share it again?

**Comment by WCSY-YG** [comment]
> can't open the image May you share it again?

![1](https://github.com/intel/intel-extension-for-transformers/assets/89191003/ad1e9538-89de-404e-a53f-11c592f1a909)

**Comment by Zhenzhong1** [comment]
@WCSY-YG Hi, please provide more details so that I can reproduce your error. The script, the model name / card_id of HF and commands.

**Comment by WCSY-YG** [comment]
> @WCSY-YG Hi, please provide more details so that I can reproduce your error. The script, the model name / card_id of HF and commands.
the details are as follows: I successfully quantized the Qwen7b model using the weight-only quantization feature and saved it locally. However, when I attempted to reload the saved model again, an error occurred as shown in the above screenshot. The code is as follows:

Python
from intel_extension_for_transformers.transformers import AutoModelForCausalLM
model_path = "Qwen/Qwen-7B"
saved_dir = "4bit_qwen7b"
model = AutoModelForCausalLM.from_pretrained(model_path, load_in_4bit=True, use_llm_runtime=False)
model.save_pretrained(saved_dir)
loaded_model = AutoModelForCausalLM.from_pretrained(saved_dir)

**Comment by Zhenzhong1** [comment]
@WCSY-YG Hi, I am not sure why you use `llm_runtime=False`. But it has been set to True as default.

Please check scripts/python_api_example.py of the main branch. My command is:
`python scripts/python_api_example.py Qwen/Qwen-7B-Chat`

I got:
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/3c5b2d45-de9a-4d9f-9351-b8c023dfeec7)


and I re-run also got:
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/533bd626-6f35-4028-a9a7-263b7f706720)

Seems good.

**Comment by WCSY-YG** [comment]
> @WCSY-YG Hi, I am not sure why you use `llm_runtime=False`. But it has been set to True as default.
> 
> Please check scripts/python_api_example.py of the main branch. My command is: `python scripts/python_api_example.py Qwen/Qwen-7B-Chat`
> 
> I got: ![image](https://private-user-images.githubusercontent.com/109137058/299905617-3c5b2d45-de9a-4d9f-9351-b8c023dfeec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTM4MDEsIm5iZiI6MTcwNjI1MzUwMSwicGF0aCI6Ii8xMDkxMzcwNTgvMjk5OTA1NjE3LTNjNWIyZDQ1LWRlOWEtNGQ5Zi05MzUxLWI4YzAyM2RmZWVjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwNzE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2FiYzM3OGY3MTEwOTFiODE0MTA3NTI4MDYxMzNlNThhNmJhNjU1NGEwYzk5ZTQ0ZGVlOTAzNDAxYTdkZjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oak_21s1N134aoNRkeemQ4qj24L8PMk7mRp-CUthKkA)
> 
> I re-ran and also got: ![image](https://private-user-images.githubusercontent.com/109137058/299905915-533bd626-6f35-4028-a9a7-263b7f706720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTM4MDEsIm5iZiI6MTcwNjI1MzUwMSwicGF0aCI6Ii8xMDkxMzcwNTgvMjk5OTA1OTE1LTUzM2JkNjI2LTZmMzUtNDAyOC1hOWE3LTI2M2I3ZjcwNjcyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwNzE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWQ1ZTUwYWRiMTIxNjU1Mjg3NDU3N2VlM2JiYjJhYjlkMTE0MzM3NGExYmMxYTVmMzNkMzhiMTM3MWJmMzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qjHRTEPl6NQwZ-5IAAX_80oFwxaqOTmOtZl8s2gvNwM)
> 
> Seems good.

I am following the example provided in the link below to quantize my model: https://github.com/intel/intel-extension-for-transformers/blob/main/docs/weightonlyquant.md. In the "PyTorch Example Code," it mentions, "You can also save and load your quantized low-bit model using the code below." Is there an issue with this example, and how should I use PyTorch to save and load the quantized model correctly?

**Comment by Zhenzhong1** [comment]
@WCSY-YG Hi, I got it
> use_llm_runtime = False

means using pytorch as backend. Please check this issue~   @changwangss 

If you want to use_llm_runtime = True, please check the `scripts/python_api_example.py` of the main branch. This script will load, convert, quantize and infernece your model. It also saves models to the local path `runtime_outs`.

**Comment by WCSY-YG** [comment]
> @WCSY-YG Hi, I got it
> 
> > use_llm_runtime = False
> 
> means using pytorch as backend. Please check this issue~ @changwangss
> 
> If you want to use_llm_runtime = True, please check the `scripts/python_api_example.py` of the main branch. This script will load, convert, quantize and infernece your model. It also saves models to the local path `runtime_outs`.

Sure, thank you very much

**Comment by changwangss** [comment]
https://github.com/intel/intel-extension-for-transformers/pull/1211 the PR fixed the issue, please use the latest version ITREX try again.
