### ISSUE TITLE
Cannot import name 'WeightOnlyLinear' when running `from intel_extension_for_transformers.transformers import AutoModelForCausalLM`

### ISSUE THREAD

**Issue by Ankur-singh** [intel/intel-extension-for-transformers#1239]
I keep getting the following error when I try to import `AutoModelForCausalLM`

```
ImportError: cannot import name 'WeightOnlyLinear' from 'neural_compressor.adaptor.torch_utils.model_wrapper' (/opt/intel/oneapi/intelpython/latest/envs/pytorch/lib/python3.9/site-packages/neural_compressor/adaptor/torch_utils/model_wrapper.py)
```

To install, I used `pip` as shown in the readme file. I tried both CPU and GPU environments but it doesn't seems to be working. I tired the following : 
- `from intel_extension_for_transformers.transformers.modeling import AutoModelForCausalLM`
- `from intel_extension_for_transformers.transformers import AutoModelForCausalLM`

Both resulted in the same error message.

**Comment by changwangss** [comment]
please use neural compressor 2.4.1
