### ISSUE TITLE
[Neural Chat] Finetuning flow on Xeon SPR for single node fails

### ISSUE THREAD

**Issue by mini-goel** [intel/intel-extension-for-transformers#1274]
Finetuning example workflow : https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/neural_chat/examples/finetuning/instruction for Single Node Xeon fails with below error:
2024-02-13 10:49:19,245 - ERROR - Exception: 'instruction'
2024-02-13 10:49:19,245 - ERROR - Exception: 'instruction'
2024-02-13 10:49:19,245 - my_app - ERROR - Exception: 'instruction'
2024-02-13 10:49:19 [ERROR] neuralchat error: LORA finetuning failed

**Comment by XinyuYe-Intel** [comment]
Hi @mini-goel , can you provide your command that run into this error?

**Comment by mini-goel** [comment]
python finetune_clm.py \
        --model_name_or_path "mistralai/Mistral-7B-v0.1" \
        --bf16 True \
        --train_file "/data/minigoel/llm/alpaca_data.json" \
        --dataset_concatenation \
        --per_device_train_batch_size 8 \
        --per_device_eval_batch_size 8 \
        --gradient_accumulation_steps 1 \
        --do_train \
        --learning_rate 1e-4 \
        --num_train_epochs 3 \
        --logging_steps 100 \
        --save_total_limit 2 \
        --overwrite_output_dir \
        --log_level info \
        --save_strategy epoch \
        --output_dir ./mistral_peft_finetuned_model \
        --peft lora \
        --use_fast_tokenizer True \
        --no_cuda \

**Comment by XinyuYe-Intel** [comment]
> python finetune_clm.py --model_name_or_path "mistralai/Mistral-7B-v0.1" --bf16 True --train_file "/data/minigoel/llm/alpaca_data.json" --dataset_concatenation --per_device_train_batch_size 8 --per_device_eval_batch_size 8 --gradient_accumulation_steps 1 --do_train --learning_rate 1e-4 --num_train_epochs 3 --logging_steps 100 --save_total_limit 2 --overwrite_output_dir --log_level info --save_strategy epoch --output_dir ./mistral_peft_finetuned_model --peft lora --use_fast_tokenizer True --no_cuda \

I've run successfully with this command. Can you check your data file "/data/minigoel/llm/alpaca_data.json" to see whether it's corrupted?

**Comment by mini-goel** [comment]
Downloading the stanford-alpaca repo and repointing the data file alpaca.json worked fine. Issue can be closed.

**Comment by XinyuYe-Intel** [comment]
That's great, closing this issue.
