### ISSUE TITLE
Unexpected msg "ERROR - The chosen retrieval type remains outside the supported scope." if retrieval_type = 'default'

### ISSUE THREAD

**Issue by redhairerINTEL** [intel/intel-extension-for-transformers#1309]
![image](https://github.com/intel/intel-extension-for-transformers/assets/32321821/bf32cd38-a075-45e0-b3cc-b1450a119179)
line45 should be elif
![image](https://github.com/intel/intel-extension-for-transformers/assets/32321821/3ba6c0fa-b84b-4a9c-8140-7f05d18aad55)

**Comment by XuhuiRen** [comment]
could be fix via https://github.com/intel/intel-extension-for-transformers/pull/1313
 
same issue for https://github.com/intel/intel-extension-for-transformers/issues/1315

**Comment by XuhuiRen** [comment]
already fixed in PR
