### ISSUE TITLE
Conflict between ipex and pytorch

### ISSUE THREAD

**Issue by redhairerINTEL** [intel/intel-extension-for-transformers#1311]
After pip install -r intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/requirements.txt, pytorch will downgrade to 2.1.0
but rebuild itrex need pytorch2.2.*
 
![image](https://github.com/intel/intel-extension-for-transformers/assets/32321821/dc3c2953-8c32-428f-a891-475a8c096d00)

**Comment by XuhuiRen** [comment]
Some new dependencies may not have updated their requirements which causing this problem.
Could be solved via force update the torch version to 2.2.0.
Validated on the local machine.
https://github.com/intel/intel-extension-for-transformers/pull/1314

**Comment by XuhuiRen** [comment]
already fixed in PR
