### ISSUE TITLE
No module named 'schema' while fine-tuning neuralchat on Gaudi2

### ISSUE THREAD

**Issue by alierenak** [intel/intel-extension-for-transformers#1436]
I am following [Intel NeuralChat v3 tutorial](https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/neural_chat/examples/finetuning/finetune_neuralchat_v3) to fine-tune custom model with my own data.

I was able to run this 10 days ago, idk what is changed since then but it seems this tutorial is broken rn. The following error is thrown when I run `finetune_neuralchat_v3.py`.

Any idea?
```
root@tmp-gaudi2:/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/finetune_neuralchat_v3# python3 finetune_neuralchat_v3.py
[WARNING|utils.py:185] 2024-03-28 14:15:58,686 >> optimum-habana v1.9.0.dev0 has been validated for SynapseAI v1.12.0 but habana-frameworks v1.13.0.463 was found, this could lead to undefined behavior!
[WARNING|utils.py:198] 2024-03-28 14:15:59,534 >> optimum-habana v1.9.0.dev0 has been validated for SynapseAI v1.12.0 but the driver version is v1.14.0, this could lead to undefined behavior!
Traceback (most recent call last):
  File "/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/finetune_neuralchat_v3/finetune_neuralchat_v3.py", line 19, in <module>
    from intel_extension_for_transformers.neural_chat.config import (
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers-1.4rc2.dev41+gc238c5b1-py3.10-linux-x86_64.egg/intel_extension_for_transformers/neural_chat/__init__.py", line 26, in <module>
    from .chatbot import build_chatbot
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers-1.4rc2.dev41+gc238c5b1-py3.10-linux-x86_64.egg/intel_extension_for_transformers/neural_chat/chatbot.py", line 19, in <module>
    from intel_extension_for_transformers.transformers.llm.quantization.optimization import Optimization
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers-1.4rc2.dev41+gc238c5b1-py3.10-linux-x86_64.egg/intel_extension_for_transformers/transformers/__init__.py", line 19, in <module>
    from .config import (
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers-1.4rc2.dev41+gc238c5b1-py3.10-linux-x86_64.egg/intel_extension_for_transformers/transformers/config.py", line 22, in <module>
    from neural_compressor.conf.config import (
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor-2.5-py3.10.egg/neural_compressor/__init__.py", line 21, in <module>
    from .config import (
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor-2.5-py3.10.egg/neural_compressor/config.py", line 21, in <module>
    from schema import And, Optional, Or, Schema
ModuleNotFoundError: No module named 'schema'
```

**Comment by lkk12014402** [comment]
> I am following [Intel NeuralChat v3 tutorial](https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/neural_chat/examples/finetuning/finetune_neuralchat_v3) to fine-tune custom model with my own data.
> 
> I was able to run this 10 days ago, idk what is changed since then but it seems this tutorial is broken rn. The following error is thrown when I run `finetune_neuralchat_v3.py`.
> 
> Any idea?
> 
> ```
> root@tmp-gaudi2:/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/finetune_neuralchat_v3# python3 finetune_neuralchat_v3.py
> [WARNING|utils.py:185] 2024-03-28 14:15:58,686 >> optimum-habana v1.9.0.dev0 has been validated for SynapseAI v1.12.0 but habana-frameworks v1.13.0.463 was found, this could lead to undefined behavior!
> [WARNING|utils.py:198] 2024-03-28 14:15:59,534 >> optimum-habana v1.9.0.dev0 has been validated for SynapseAI v1.12.0 but the driver version is v1.14.0, this could lead to undefined behavior!
> Traceback (most recent call last):
>   File "/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/finetune_neuralchat_v3/finetune_neuralchat_v3.py", line 19, in <module>
>     from intel_extension_for_transformers.neural_chat.config import (
>   File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers-1.4rc2.dev41+gc238c5b1-py3.10-linux-x86_64.egg/intel_extension_for_transformers/neural_chat/__init__.py", line 26, in <module>
>     from .chatbot import build_chatbot
>   File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers-1.4rc2.dev41+gc238c5b1-py3.10-linux-x86_64.egg/intel_extension_for_transformers/neural_chat/chatbot.py", line 19, in <module>
>     from intel_extension_for_transformers.transformers.llm.quantization.optimization import Optimization
>   File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers-1.4rc2.dev41+gc238c5b1-py3.10-linux-x86_64.egg/intel_extension_for_transformers/transformers/__init__.py", line 19, in <module>
>     from .config import (
>   File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers-1.4rc2.dev41+gc238c5b1-py3.10-linux-x86_64.egg/intel_extension_for_transformers/transformers/config.py", line 22, in <module>
>     from neural_compressor.conf.config import (
>   File "/usr/local/lib/python3.10/dist-packages/neural_compressor-2.5-py3.10.egg/neural_compressor/__init__.py", line 21, in <module>
>     from .config import (
>   File "/usr/local/lib/python3.10/dist-packages/neural_compressor-2.5-py3.10.egg/neural_compressor/config.py", line 21, in <module>
>     from schema import And, Optional, Or, Schema
> ModuleNotFoundError: No module named 'schema'
> ```

hi, the `schema` version has some problems due to its own upgrade. So, it downgrades to 0.7.5.

can you try `pip uninstall schema && pip install schema==0.7.5`?

Thanks~

**Comment by alierenak** [comment]
This seems worked. Thanks!
