### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by Aisuko** [intel/intel-extension-for-transformers#1461]
<img width="1463" alt="Screenshot 2024-04-08 at 9 40 37 PM" src="https://github.com/intel/intel-extension-for-transformers/assets/8053949/44b8a655-b965-4aea-aae1-3105db2df705">

**Comment by a32543254** [comment]
please use command:
pip install datasets 
to install datasets module

**Comment by Aisuko** [comment]
Thank you @a32543254 , I mean might be  added datasets to the requirements.txt that would be better.
