### ISSUE TITLE
INT4 Inference (CPU) example from README is not working on Windows 11

### ISSUE THREAD

**Issue by sumeetdas** [intel/intel-extension-for-transformers#1480]
INT4 Inference (CPU) example from README is not working on Windows 11.

```python
from transformers import AutoTokenizer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM
model_name = "C:\\llm\\neural-chat-7b-v3-1"     
prompt = "Once upon a time, there existed a little girl,"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
inputs = tokenizer(prompt, return_tensors="pt").input_ids

model = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True)
outputs = model.generate(inputs)
```

Error:

```bash
$ python3 new.py
2024-04-14 19:49:11 [INFO] CPU device is used.
2024-04-14 19:49:11 [INFO] Applying Weight Only Quantization.
2024-04-14 19:49:11 [INFO] Using LLM runtime.
runtime_outs/ne_mistral_q_nf4_jblas_cfp32_g32.bin existed, will use cache file. Otherwise please remove the file
AVX:1 AVX2:1 AVX512F:0 AVX_VNNI:1 AVX512_VNNI:0 AMX_INT8:0 AMX_BF16:0 AVX512_BF16:0 AVX512_FP16:0
Traceback (most recent call last):
  File "C:\intel_neural_speed\new.py", line 10, in <module>
    outputs = model.generate(inputs)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\intel_extension_for_transformers\llm\runtime\graph\__init__.py", line 149, in generate
    self.init_from_bin(self.model_type, self.bin_file, batch_size=self.batch_size,
  File "C:\Users\Sumeet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\intel_extension_for_transformers\llm\runtime\graph\__init__.py", line 135, in init_from_bin
    generate_kwargs["threads"] = len(os.sched_getaffinity(0))
                                     ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'os' has no attribute 'sched_getaffinity'
```

Also, another suggestion, the README example should make it clear that we need to checkout the hugging face repository of the model to use and then use its local path as a `model_name`. For example, I checked out the `Intel/neural-chat-7b-v3-1` [repository](https://huggingface.co/Intel/neural-chat-7b-v3-1/tree/main) from HuggingFace website in `C:\\llm\\neural-chat-7b-v3-1` and then passed it as an argument to both `AutoTokenizer.from_pretrained` and ` AutoModelForCausalLM.from_pretrained`.

**Comment by Zhenzhong1** [comment]
@sumeetdas 
Hi, for this ` File "C:\Users\Sumeet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\intel_extension_for_transformers\llm\runtime\graph\__init__.py", line 135, in init_from_bin
    generate_kwargs["threads"] = len(os.sched_getaffinity(0))`

I found your ITREX version might be too old.

The latest code about your error is: https://github.com/intel/neural-speed/blob/main/neural_speed/__init__.py#L214-L225, which means if you run the programme on the windows11, it should not get into the branch `os.sched_getaffinity(0)`.

So, do you mind reinstall the latest ITREX & neural speed, and then try again?
uninstall first and then
`pip install neural-speed` + ` pip install intel-extension-for-transformers`

latest verison screenshots:
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/d21862e2-4fcd-4b31-9112-66fc1834393e)

**Comment by Zhenzhong1** [comment]
@sumeetdas thanks for your suggestions!!! The latest code has taken your advice already.

The example can download the model from HF and inference directly, no matter you use local models or HF models.

The README example screenshot:
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/af278107-e824-4477-b3ee-22fd41533613)
