### ISSUE TITLE
[Qlora on CPU Error] python finetune_clm.py with Qwen-14B-Chat 

### ISSUE THREAD

**Issue by cailuyu** [intel/intel-extension-for-transformers#1484]
When we do Qlora with "python finetune_clm.py" on Intel(R) Xeon(R) CPU E5-2680 v4
I got following message and Error：

2024-04-16 16:15:53 [INFO] None device is used.
2024-04-16 16:15:53 [INFO] Applying Weight Only Quantization.
...
2024-04-16 16:18:17 [INFO] Save deploy yaml to /opt/luyu/git/itrex/intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/nc_workspace/2024-04-16_16-15-41/deploy.yaml
04/16/2024 16:18:17 - ERROR - intel_extension_for_transformers.neural_chat.chatbot - Exception: None device Unsupported weight only quantization!
04/16/2024 16:18:17 - ERROR - intel_extension_for_transformers.neural_chat.utils.error_utils - neuralchat error: LORA finetuning faile

**Comment by cailuyu** [comment]
Here is the full CMD:
python finetune_clm.py \
        --model_name_or_path Qwen/Qwen-14B-Chat \
        --bf16 True \
        --train_file /data/training/training_data.json \
        --per_device_train_batch_size 1 \
        --per_device_eval_batch_size 1 \
        --gradient_accumulation_steps 8 \
        --do_train \
        --do_eval \
        --validation_split_percentage 5 \
        --learning_rate 1e-4 \
        --num_train_epochs 3 \
        --logging_steps 100 \
        --save_total_limit 2 \
        --overwrite_output_dir \
        --log_level info \
        --save_strategy epoch \
        --output_dir ./llama_peft_finetuned_model \
        --peft lora \
        --use_fast_tokenizer false \
        --qlora \
        --trust_remote_code \
        --device auto \
        --max_train_samples 500

**Comment by XinyuYe-Intel** [comment]
Hi @cailuyu , this issue is fixed in this [PR 1503](https://github.com/intel/intel-extension-for-transformers/pull/1503), you can give it a try. BTW, you need to add `--lora_target_modules c_proj` as well in your cmd since peft haven't registered Qwen-14B-Chat.

**Comment by cailuyu** [comment]
Thanks! it has been fix.
But there is still an "unsupported compute_dtype" error when I set --bf16 True and --qlora.
I hardcode the compute_dtype as workaround

**Comment by XinyuYe-Intel** [comment]
> Thanks! it has been fix. But there is still an "unsupported compute_dtype" error when I set --bf16 True and --qlora. I hardcode the compute_dtype as workaround

That's weird, I haven't met such error when I set --bf16 True and --qlora.
