### ISSUE TITLE
NeuralChat TTS plugin unable to initialize due to missing dependency: librosa

### ISSUE THREAD

**Issue by alexsin368** [intel/intel-extension-for-transformers#1490]
The NeuralChat TTS plugin is unable to initialize when building the chatbot due to check_tts_dependency() in intel_extension_for_transformers/neural_chat/chatbot.py returning False. Image shown below. This is because the library "librosa" is not in the requirements file.

There are two ways to fix this (which I have verified myself), and will let the team decide:

1. Add librosa back into the requirements.txt file for the audio TTS plugin: https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/requirements.txt

2. Remove librosa in chatbot.py: https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat/chatbot.py#L35

![image](https://github.com/intel/intel-extension-for-transformers/assets/109180236/05d132d1-8e38-4567-9f73-4252ed5ad6f4)

**Comment by kta-intel** [comment]
librosa added back to requirements.txt file in https://github.com/intel/intel-extension-for-transformers/pull/1496
