### ISSUE TITLE
Frontend(gradio) string output is not like streaming

### ISSUE THREAD

**Issue by redhairerINTEL** [intel/intel-extension-for-transformers#1524]
stream default is True but string output is not like streaming
![image](https://github.com/intel/intel-extension-for-transformers/assets/32321821/0660fc3e-61c2-463a-a116-5d11b63a2ec4)

**Comment by kevinintel** [comment]
Thanks for reporting it, we will check the issue

**Comment by zhentaoyu** [comment]
Hi, @redhairerINTEL, can you paste your codes and env version so that I can reproduce your issue? Thanks

**Comment by redhairerINTEL** [comment]
Per discussion, I used neuralchat as backend and gradio as frontend.
If you are right owner, please help to assign to right owner.

**Comment by zhentaoyu** [comment]
Hi, @lvliang-intel, @letonghan, I'm not familiar with the neural chat streaming. could you please help with this issue? Thanks a lot.
