### ISSUE TITLE
Compatibility for other platforms, AMD, etc.

### ISSUE THREAD

**Issue by rain7996** [intel/intel-extension-for-transformers#1649]
Can this extension run Llama3 on AMD CPU without any GPUs?

I followed the guide for docker usage. When I come into the command:

> docker compose run devel python setup.py sdist

I met the following error:

> LookupError: setuptools-scm was unable to detect version for /app/intel-extension-for-transformers.

The intact log is as follows:

> WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 

> WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
> [+] Running 1/1
>  ✔ devel Pulled                                                                                              0.9s 
> /usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
>   _torch_pytree._register_pytree_node(
> /usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
>   _torch_pytree._register_pytree_node(
> /usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
>   _torch_pytree._register_pytree_node(
> /usr/local/lib/python3.10/dist-packages/setuptools/__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
> !!
> 
>         ********************************************************************************
>         Requirements should be satisfied by a PEP 517 installer.
>         If you are using pip, you can try `pip install --use-pep517`.
>         ********************************************************************************
> 
> !!
>   dist.fetch_build_eggs(dist.setup_requires)
> [07/02/24 09:38:55] WARNING  toml section missing 'pyproject.toml does not contain a       pyproject_reading.py:42
>                              tool.setuptools_scm section'                                                         
> Traceback (most recent call last):
>   File "/app/intel-extension-for-transformers/setup.py", line 289, in <module>
>     setup(
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 104, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 147, in setup
>     _setup_distribution = dist = klass(attrs)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 307, in __init__
>     _Distribution.__init__(self, dist_attrs)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 283, in __init__
>     self.finalize_options()
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 658, in finalize_options
>     ep(self)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 678, in _finalize_setup_keywords
>     ep.load()(self, ep.name, value)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools_scm/_integration/setuptools.py", line 101, in version_keyword
>     _assign_version(dist, config)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools_scm/_integration/setuptools.py", line 56, in _assign_version
>     _version_missing(config)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
>     raise LookupError(
> LookupError: setuptools-scm was unable to detect version for /app/intel-extension-for-transformers.
> 
> Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
> 
> For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

How can I deal with it? Thanks a lot.

**Comment by a32543254** [comment]
could run following command ? 
pip install setuptools-scm

then reinstall our code

**Comment by rain7996** [comment]
> could run following command ? pip install setuptools-scm
> 
> then reinstall our code

It prompts that requirements are already satisfied when I run the command:
> pip install setuptools-scm 

However, the same error appears again.

BTW, what does the following  warning mean? I see it in the issue  https://github.com/huggingface/transformers/issues/27684. I have no idea about what should I do. 

> /usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.

Really need your help. Thank you very much.

**Comment by a32543254** [comment]
Sorry, just synced with team member 
Our docker is not support AMD, you could try them on intel HW

**Comment by rain7996** [comment]
> Sorry, just synced with team member Our docker is not support AMD, you could try them on intel HW

fine, sincerely appreciate.

**Comment by a32543254** [comment]
Hi, I will close this issue if you don't have concerns
