### ISSUE TITLE
How can I use Intel extension for transformers on HPUs?

### ISSUE THREAD

**Issue by sleepingcat4** [intel/intel-extension-for-transformers#1664]
I personally love this library ```intel extension for transformers``` and I want to use this library on Intel HPUs as well (gaudi2) to be exact. is there any way I could do it?

**Comment by a32543254** [comment]
please refer to https://github.com/intel/intel-extension-for-transformers/tree/main/examples/habana

**Comment by sleepingcat4** [comment]
@a32543254 I have a question. 

```from intel_extension_for_transformers.transformers.modeling.modeling_gaudi import adapt_transformers_to_gaudi``` 

if this line adapts any transformer model for gaudi framework then don't I explicitly have to mention "hpu"? like how you do it? do you use ipex or torch to find whether the node has **hpu** or not?

**Comment by sleepingcat4** [comment]
@a32543254 another! Can't use device_map to use hpu for my model if I load it using Intel extension for transformers?

```model = AutoModelForCausalLM.from_pretrained(args.model_name_or_path, torch_dtype=model_dtype, **model_kwargs)```

**Comment by sleepingcat4** [comment]
@a32543254 just asking! I found this https://docs.habana.ai/en/latest/PyTorch/Inference_on_PyTorch/Inference_Using_FP8.html

And was wondering why the habana optimum and habana framework's have such a bad software philosophy. Cuz it makes the work daunting and the documentation is very very poor. I had another question recently I used my model both on gaudi2 and datascentre max gpus (xpus) and saw there gaudi2 wasn't much different from XPUs per say. I quantised the XPU model using 4bit and then loaded and inference took **3.47 minutes** and gaudi takes anywhere between **1.47-2.5** minutes. I thought the jump between gaudi2 and xpu would be really significant like gaud2 will take 1 minute and xpu will takes 3.47 minutes. **(one xpu)** btw. 

I was wondering is there any optimizations that you guys at Intel do or this is the best I can receive? btw I am using default docker container from intel's **tei gaudi** repo

**Comment by a32543254** [comment]
Thanks for your usage of habana.
Actually we just use optimum-habana as our backend. so for more habana's detail, please go to  
https://github.com/huggingface/optimum-habana, to raise your issue.

**Comment by sleepingcat4** [comment]
@a32543254 Can I ask for a feature request? Where in the next version intel_extension_for_transformers allow using HPU as seamlessly XPUs are allowed to be loaded and used? 

Or I should raise this on the habana repo?

**Comment by a32543254** [comment]
Please raise feature request on habana repo
