### ISSUE TITLE
[Feature request] Support for Flashattention 3

### ISSUE THREAD

**Issue by sleepingcat4** [intel/intel-extension-for-transformers#1665]
I had previous programmed for XLA and Cuda machines but recently while trying out HPUs, I quite seem to like it. Even though the software stake is awful and there's no actual helpline/documentation to refer to except reading the code which itself is written for CLI interface in mind. 

I was thinking to use Intel Gaudi2 for some projects and develop new architecture since I have some clusters. I was curious if FlasAttention support already exists and if not then can the devs offer support for FlashAttention 3?

https://github.com/Dao-AILab/flash-attention

**Comment by a32543254** [comment]
Really happy you are using and interesting habana.
we do put a lot effort on habana now, and for usage of habana, you can also reach to repo 
https://github.com/huggingface/optimum-habana, they should provide your more info about habana side.
