### ISSUE TITLE
Any benchmarks having been made between llama.cpp and  ITREX graph? 

### ISSUE THREAD

**Issue by yingfeng** [intel/intel-extension-for-transformers#183]
According to the publication of `An Efficient Sparse Inference Software Accelerator for Transformer-based Language Models on CPUs`, it seems the major improvements of this project is to provide a faster sgemm kernel for model compression. Since ITREX graph is also an inference engine for x86 CPUs, any performance comparison has been made between it and llama.cpp ?

**Comment by kevinintel** [comment]
Yes, we ever compared with llama.cpp and got better performance on x86 CPUs.
We will share the performance data in the future, but you can try ITREX first.

**Comment by airMeng** [comment]
https://medium.com/@NeuralCompressor/llm-performance-of-intel-extension-for-transformers-f7d061556176

@yingfeng  does this help?
