### ISSUE TITLE
example links in Neural Engine doc goes 404

### ISSUE THREAD

**Issue by kaiyaointel** [intel/intel-extension-for-transformers#3]
The examples in this readme

https://github.com/intel/intel-extension-for-transformers/blob/main/examples/deployment/README.md
![image](https://user-images.githubusercontent.com/86637189/204739113-cd839855-ca8e-427c-8ee7-0b71bffd1633.png)

cannot be opened. It seems they direct to ```develop``` branch which has been removed.

**Comment by VincyZhang** [comment]
Thanks for reminding! 
Fixed in this PR: https://github.com/intel/intel-extension-for-transformers/pull/4
