### ISSUE TITLE
intel-extension-for-transformers/examples/huggingface/pytorch/text-to-image/quantization /qat/

### ISSUE THREAD

**Issue by yrf200112** [intel/intel-extension-for-transformers#308]
how to get the 20000 images dataset from opensource LAION400m?I try to follow the steps with your readme docs, but can't find that.

**Comment by kevinintel** [comment]
LAION400m website:
https://laion.ai/blog/laion-400-open-dataset/
you can find dataset in
https://deploy.laion.ai/8f83b608504d46bb81708ec86e912220/dataset/

**Comment by XinyuYe-Intel** [comment]
Below command is for getting fp32 result.
```bash
python text2images.py \
    --pretrained_model_name_or_path runwayml/stable-diffusion-v1-5 \
    --captions "a photo of an astronaut riding a horse on mars"
```

**Comment by yrf200112** [comment]
Thank you very much! @XinyuYe-Intel
