### ISSUE TITLE
is kv cache used for inference?

### ISSUE THREAD

**Issue by njjry** [intel/intel-extension-for-transformers#378]
Hi 

I would like to use the inference code but I want to know if it uses kv cache? And can I configure the size of the kv cache for inference?

Thanks

**Comment by a32543254** [comment]
Yes, K V cache is automatically use in our inference, 
and the size of the kv cache will be automatically malloced depends on your inputs pormpt, you don't need configure any thing.

**Comment by njjry** [comment]
Thanks for the explanation!


- Runyu
