### ISSUE TITLE
The method in the official guide does not seem to be in the latest release.

### ISSUE THREAD

**Issue by park12sj** [intel/intel-extension-for-transformers#394]
https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/llm/runtime/graph#2-run-llm-with-python-api 
I'd like to use this guide. However, it is not in the latest release.

latest release : 1.1.1
```
from .config import (
    AutoDistillationConfig,
    DistillationConfig,
    FlashDistillationConfig,
    TFDistillationConfig,
    NASConfig,
    Provider,
    PruningConfig,
    QuantizationConfig,
    WEIGHTS_NAME,
    DynamicLengthConfig,
    BenchmarkConfig,
    PrunerV2,
    
)
from .distillation import (
    DistillationCriterionMode,
    SUPPORTED_DISTILLATION_CRITERION_MODE,
)
from .modeling import OptimizedModel, AutoModelForCausalLM
from .mixture.auto_distillation import AutoDistillation
from .nas import NAS
from .optimizer import NoTrainerOptimizer, Orchestrate_optimizer
from .optimizer_tf import TFOptimization
from .pruning import PrunerConfig, PruningMode, SUPPORTED_PRUNING_MODE
from .quantization import QuantizationMode, SUPPORTED_QUANT_MODE
from .utils import metrics
from .utils import objectives
from .utils.utility import LazyImport
```

https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/transformers/__init__.py
It's in the main branch. However, the following command fails when main branch is installed.
pip install git+https://github.com/intel/intel-extension-for-transformers.git

Do you have the latest release update plan or build script based on main?

I wonder if there is an additional guide to AutoModelForCausalLM.

**Comment by hshen14** [comment]
@park12sj Thanks for your trying. We will be releasing v1.2 today so please expect a new version in a couple of hours.

**Comment by park12sj** [comment]
It is well used in version 2.1.
