### ISSUE TITLE
Inference ONNX format model

### ISSUE THREAD

**Issue by bmtuan** [intel/intel-extension-for-transformers#459]
Hi guys,
Are you planning to inference onnx format model soon?

**Comment by kevinintel** [comment]
https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/llm/runtime/deprecated/docs/deploy_and_integration.md

**Comment by kevinintel** [comment]
if you don't have other questions, i will close this issue.

**Comment by kevinintel** [comment]
Hi bmtuan,
can you use the example?

**Comment by dyt06** [comment]
C:\Windows\system32>D:\o\1\run_whisper.exe -l zh -m D:\o\1\whisper_gpu_int8_gpu-cuda_model.onnx -f D:\o\1\1.wav -osrt
whisper_init_from_file_no_state: loading model from 'D:\o\1\whisper_gpu_int8_gpu-cuda_model.onnx'
whisper_model_load: loading model
NE_ASSERT: E:\whisper_opt\intel_extension_for_transformers\llm\runtime\graph\core\ne_layers.c:643: wtype != NE_TYPE_COUNT

**Comment by intellinjun** [comment]
P

> C:\Windows\system32>D:\o\1\run_whisper.exe -l zh -m D:\o\1\whisper_gpu_int8_gpu-cuda_model.onnx -f D:\o\1\1.wav -osrt whisper_init_from_file_no_state: loading model from 'D:\o\1\whisper_gpu_int8_gpu-cuda_model.onnx' whisper_model_load: loading model NE_ASSERT: E:\whisper_opt\intel_extension_for_transformers\llm\runtime\graph\core\ne_layers.c:643: wtype != NE_TYPE_COUNT

This method uses the cpp model for inference, and the onnx model is not supported for the time being, if you want to use the onnx model for inference, please refer to ：https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/llm/runtime/deprecated/docs/deploy_and_integration.md
