### ISSUE TITLE
Support for k-means clustered quantisations?

### ISSUE THREAD

**Issue by ElliottDyson** [intel/intel-extension-for-transformers#480]
Hello,

I was just wondering if k-means clustered (mixed 6-bit and 4-bit) quantisations will be supported? Or if not currently on the roadmap, if you would consider it?
- Given their much better performance of perplexity for a given size of model to be loaded in.

For further information: See Llama.cpp and the GGUF file format for reference.

Thank you

**Comment by zhewang1-intc** [comment]
Hi, we currently don't support k-means clustered quantization, and it is not in out roadmap. Can you please provide an example of using k-means clustered to quantize the KxN weight into a low-bit weight?

**Comment by zhewang1-intc** [comment]
hi, we have noticed some techs for generating quantization LUT using k-means clustered. Does your k-means quantization refer to this?

**Comment by ElliottDyson** [comment]
> hi, we have noticed some techs for generating quantization LUT using k-means clustered. Does your k-means quantization refer to this?

Sorry about my late reply, I've been trying to look into it some more but don't understand the full implementation myself in terms of the k-quanta themselves. However something I was able to find is the splits of quantisations that are used:

q2_k: Uses Q4_K for the attention.vw and feed_forward.w2 tensors, Q2_K for the other tensors.

q3_k_m: Uses Q4_K for the attention.wv, attention.wo, and feed_forward.w2 tensors, else Q3_K

q4_k_m: Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K

q5_k_m: Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K

Q4_k_m and Q5_k_m seem to be the most common and well received quantisation methods, Q5_k_m showing very little degradation in quality over 8bit quantisation, and Q4_k_m still being good if you need the extra memory savings.

**Comment by zhewang1-intc** [comment]
> > hi, we have noticed some techs for generating quantization LUT using k-means clustered. Does your k-means quantization refer to this?
> 
> Sorry about my late reply, I've been trying to look into it some more but don't understand the full implementation myself in terms of the k-quants themselves. However something I was able to find is the splits of quantisations that are used:
> 
> q2_k: Uses Q4_K for the attention.vw and feed_forward.w2 tensors, Q2_K for the other tensors.
> 
> q3_k_m: Uses Q4_K for the attention.wv, attention.wo, and feed_forward.w2 tensors, else Q3_K
> 
> q4_k_m: Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K
> 
> q5_k_m: Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K
> 
> Q4_k_m and Q5_k_m seem to be the most common and well received quantisation methods, Q5_k_m showing very little degradation in quality over 8bit quantisation, and Q4_k_m still being good if you need the extra memory savings.
> 
> Edit: My apologies, I've actually found the proper documentation for it just now: [ggerganov/llama.cpp#1684](https://github.com/ggerganov/llama.cpp/pull/1684)

hi, I noticed the pr of ggml you provided, in fact, we currently support Q4_ 0 (ggml 4bit quantization) and Q4_J(itrex 4bit quantization, including S4/NF4, etc.) mixed k-quant quantization. We will support more quantization types and Q2_ J (itrex 2bit quantization) is WIP, please stay tuned!

Ps: itrex is the abbreviation for Intel extension for transformer
