### ISSUE TITLE
Please add in requirements file version of neural-compressor <= 1.14.2

### ISSUE THREAD

**Issue by aahouzi-intel** [intel/intel-extension-for-transformers#49]
It seems like ITREX is not compatible with INC 2.0 API. It would be helpful to add <= 1.14.2 constraint on neural-compressor.

Also, in your demo of BERT-mini, there is an import line that doesn't pass here: https://github.com/intel/intel-extension-for-transformers/blob/main/examples/deployment/neural_engine/sparse/bert_mini/run_glue.py#L29

When changing it with the following it starts working:

"""from intel_extension_for_transformers.optimization.model import OptimizedModel
    from intel_extension_for_transformers.optimization.config import QuantizationConfig
    from intel_extension_for_transformers.optimization.utils import metrics, objectives"""

Thanks :)

**Comment by kevinintel** [comment]
compatible with INC 2.0 API is WIP

**Comment by kevinintel** [comment]
we will fix the bugs in next release

**Comment by kevinintel** [comment]
Can you share your ITREX installation info?

**Comment by aahouzi-intel** [comment]
- I installed it simply via pip: In fact, it's even more complicated than that, you can try and create a new conda env, and when u install ITREX via pip it doesn't even install neural-compressor as a dependency, and therefore u'll have errors from the first import line.
- And, when you try to install INC, ofc the user will go directly to latest version 2.0, and then will realize that it's still not supported by ITREX when an error arises, then goes back to 1.14.2 INC where it works.
- I think if pip installation is still on beta, it's better not to put it in README as the first preferred installation option for ITREX, or fix this issue, so that users can get started quickly with this new library.

Thanks :)

**Comment by kevinintel** [comment]
we will release v1.0 and fit INC 2.0, the date is close.
