### ISSUE TITLE
What is the system requirement to run the sample code?

### ISSUE THREAD

**Issue by sungkim11** [intel/intel-extension-for-transformers#531]
What is the system requirement to run the following sample code? 

from transformers import AutoTokenizer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig

model_name = "Intel/neural-chat-7b-v1-1"     # Hugging Face model_id or local model
config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4")
prompt = "Once upon a time, a little girl"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
inputs = tokenizer(prompt, return_tensors="pt").input_ids

model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=config)
gen_tokens = model.generate(inputs, max_new_tokens=300)
outputs = tokenizer.batch_decode(gen_tokens)

**Comment by zhenwei-intel** [comment]
The CPU can support the avx512 instruction set, and we recommend the RAM bigger than 16GB.

**Comment by sungkim11** [comment]
Ok.... My CPU does not support avx512. Maybe I should have bought AMD CPU. What can I use?

**Comment by DDEle** [comment]
Don't worry, we just supported AVX2 fp32 (`compute_dtype`) inference in #493. In addition, if you are using a 12th+ Core™ Processor, stay tune as we are support int8 inference with AVX_VNNI.

BTW, [AMD client CPU does not support AVX512 either](https://en.wikichip.org/wiki/amd/ryzen_9/5900x) if you are referring client products.

**Comment by DDEle** [comment]
AVX_VNNI support has been added in #565. You can enable it by setting `comput_dtype` to int8, which should outperform llama.cpp a lot on 12/13th gen Core CPUs.

@yuchengliu1 are working to squeeze some more performance based on the hybrid architecture.

Feel free to reopen the issue if you have further questions.

**Comment by amir1m** [comment]
Hi @DDEle , I am trying to build the graph. I followed the steps from README. After `cmake .. -G Ninja` , when I run `ninja` , getting following error:

> /home/datascience/intel-extension-for-transformers/intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h:24:32: error: attribute(target("avx512bf16")) is unknown
>  #pragma GCC target("avx512bf16")

Even tried disabling AVX 512 as, `cmake -G Ninja -DNE_AVX512=OFF -DNE_AVX512_VBMI=OFF -DNE_AVX512_VNNI=OFF` , still the same results.
I am running Linux on Intel(R) Xeon(R) Platinum 8167M CPU @ 2.00GHz

**Comment by DDEle** [comment]
Hi @amir1m,
Please check https://github.com/intel/intel-extension-for-transformers/issues/726#issuecomment-1820037722 for detailed explanation and solution.
