### ISSUE TITLE
Adding Contributors section to the readme.md

### ISSUE THREAD

**Issue by mohitd404** [intel/intel-extension-for-transformers#575]
Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**Issue type**

- [✅] Docs

Expected outcome:-
![3](https://github.com/intel/intel-extension-for-transformers/assets/146939900/bd403814-b704-4235-b4ab-76b27f4871c4)

 @hshen14 kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by hshen14** [comment]
Close it per the discussion in PR thread.
