### ISSUE TITLE
run_llama: [FAIL]	XTILE_DATA request failed: -1: Invalid argument

### ISSUE THREAD

**Issue by cphoward** [intel/intel-extension-for-transformers#652]
I am trying to run the examples in ["Run LLM with Python Script"](https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/llm/runtime/graph#1-run-llm-with-python-script). I can quantize, but I cannot run inference with `llama` due the following error:

``` sh
python scripts/run.py /path/to/llama/model --weight_dtype int4 -p "She opened the door and see"
...
run_llama: [FAIL]	XTILE_DATA request failed: -1: Invalid argument
```

How do I overcome this error?

I am running this on Xeon Sapphire Rapids on Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux.

Oddly, I can run inference fine for ["Chat with LLaMA2"](https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/llm/runtime/graph#3-chat-with-llama2), but quantization does not work.

**Comment by DDEle** [comment]
Hi there, it seems that you are using a CPU with AMX instructions (probably SPR) with a Linux kernel without [support of requesting AMX usage](https://www.phoronix.com/news/Intel-AMX-Lands-In-Linux). 


> the code is to to invoke a Linux system call to request access to Intel® AMX features. This is performed using the arch_prctl(2) based mechanism for applications to request usage of the Intel® AMX features. Specific information is described in the [Linux kernel documentation](https://www.kernel.org/doc/Documentation/x86/xstate.rst).
> 
> https://www.intel.com/content/www/us/en/developer/articles/code-sample/advanced-matrix-extensions-intrinsics-functions.html (2nd section of _Code sample walkthrough_)

I also found that [some users reports that AMX is unavailable on VMs](https://www.intel.com/content/www/us/en/support/articles/000094735/software.html). Not sure if that is your case.

**Comment by cphoward** [comment]
I can confirm this indeed was due to the kernel lacking support. Using a kernel >= 5.16 did the trick.

See https://lwn.net/Articles/874846/ for kernel details.
