### ISSUE TITLE
Problem loading pytorch model

### ISSUE THREAD

**Issue by attafosu** [intel/intel-extension-for-transformers#67]
After quantizing pytorch model model with neural-compressor and following the [deployment doc](https://github.com/intel/intel-extension-for-transformers/blob/main/examples/huggingface/pytorch/deployment_README.md), I'm unable to load the model.

`compile` throws the following error:
`TypeError: Got unsupported ScalarType BFloat16`

Is there anything I may be missing? or `compile` doesn't support quantized models?

**Comment by xin3he** [comment]
Hi @attafosu, Neural Engine supports pure INT8 quantization, please set `excluded_precisions = ["bf16"]` in Config when doing quantization.

**Comment by a32543254** [comment]
Yes, like he, xin said, you could give Neural Engine a pure INT8 quantization, 
Then during **compile** process, 
Neural Engine will do optimize to generate INT8/BF16 mix precision graph to do inference.
You still could get performance gain from INT8/BF16 mix precision
