### ISSUE TITLE
TypeError: Unspported model type mistral!   for "Intel/neural-chat-7b-v3"

### ISSUE THREAD

**Issue by philipshurpik** [intel/intel-extension-for-transformers#678]
Hi!
I'm trying to use code from this tutorial:
https://medium.com/@NeuralCompressor/the-practice-of-supervised-finetuning-and-direct-preference-optimization-on-habana-gaudi2-a1197d8a3cd3

```
from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig
model_name = "Intel/neural-chat-7b-v3"
...
model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=config)
...

```
Using the latest nightly version of this library: 
pip install -i https://test.pypi.org/simple/ intel-extension-for-transformers

But get error:
  File "/home/philip/envs/llm/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/__init__.py", line 61, in __import_package
    raise TypeError("Unspported model type {}!".format(model_name))
TypeError: Unspported model type mistral!

**Comment by kevinintel** [comment]
https://github.com/intel/intel-extension-for-transformers/pull/684
fix it

**Comment by philipshurpik** [comment]
thanks!  
can you please release new version build in pip?

**Comment by kevinintel** [comment]
# install nightly version
pip install -i https://test.pypi.org/simple/ intel-extension-for-transformers
