### ISSUE TITLE
Need an End to End Workflow to Stand Up Demo 

### ISSUE THREAD

**Issue by martystack** [intel/intel-extension-for-transformers#694]
I've followed the instructions at

https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/llm/runtime/graph

and I've hit several snags. First of all several steps fail as a result of not having the packages on the system, so I've had to run and then stop to install libraries like torch, accelerate, pydub, fschat, shortuuid.....

Please provide instructions from a base OS image of how to install and get up and running. This documentation is not sufficient. I'm happy to assist in this process.

**Comment by zhenwei-intel** [comment]
Please run `pip install -r requirements.txt` first, and then execute `pip install sentencepiece`. 

I will update package `sentencepiece` to the `requirements.txt` file. 

Thank you for your feedback.
