### ISSUE TITLE
Any plan to support Falcon models and 4bit quantization

### ISSUE THREAD

**Issue by tarunmcom** [intel/intel-extension-for-transformers#70]
This is great repo. I just want to know is there plan to support falcon inferencing on intel hardware. As falcon can be used for commercial purpose. At least if revenue in less than 5million. Many small companies will be interesting in that.

**Comment by tarunmcom** [comment]
> We plan to provide Falcon inference, the 4bit quantization will be weight-only quantizaion.
Thanks, I am able to quantize to 4bit falcon using` ./build/bin/quant_falcon --model_file ${output_path}/ne-f32.bin --out_file ${output_path}/ne-q4_j.bin --bits 4`. Is this simply weight conversion or some 7sophisticated technique of quantization like GPTQ/GGML? Which quantization should I use to keep the maximum accuracy on Sappire Rapids, any suggestion?

**Comment by kevinintel** [comment]
It's ggml like quantization.
gptq example is here: https://github.com/intel/intel-extension-for-transformers/pull/98

**Comment by kevinintel** [comment]
Hi @tarunmcom,
I will close it if you don't have concerns.
