### ISSUE TITLE
Which, 4th Gen Intel® Xeon® Processors, Sapphire Rapids?

### ISSUE THREAD

**Issue by tarunmcom** [intel/intel-extension-for-transformers#71]
Can you please share exact server config from CPUs to RAM to fine tune the models on Intel without GPU?

**Comment by VincyZhang** [comment]
SPR are borrowed from endeavor, 
<head>
</head>
<body>


OS | Rocky Linux 8.7 (Green Obsidian) |
-- | -- 
Kernel | 4.18.0-372.32.1.el8_6.crt2.x86_64 |
Microcode | 0x2b000190 |
IRQ Balance | Enabled |
CPU Model | Intel(R) Xeon(R) Platinum 8480+ |
Base   Frequency | N/A |
Maximum   Frequency | 2.0GHz |
CPU(s) | 224 |
Thread(s)   per Core | 2 |
Core(s)   per Socket | 56 |
Socket(s) | 2 |
NUMA   Node(s) | 8    (SNC4) |
RAM | 105G |
Turbo | enabled |

</body>
</html>

**Comment by kevinintel** [comment]
Hi [tarunmcom](https://github.com/tarunmcom), can we close this issue?
