### ISSUE TITLE
bug: Dockerfile cannot run inference 

### ISSUE THREAD

**Issue by tikikun** [intel/intel-extension-for-transformers#715]
![image](https://github.com/intel/intel-extension-for-transformers/assets/22268502/6a7b9ec0-1a1d-41f4-8c60-f788770db3c7)

Cannot run using installation from the Dockerfile in docker folder, on intel 13700k

**Comment by yuchengliu1** [comment]
Have you directly built and run the project on native Windows or WSL?

**Comment by tikikun** [comment]
no i use it on linux debian

**Comment by yuchengliu1** [comment]
You can update your code and rebuild our code. #675 seems report the same error as yours, and we have fixed it. If crash still happens, please provide your quantization command. Thank you.

**Comment by kevinintel** [comment]
Hi , I will close this issue if you don't have concerns.
