### ISSUE TITLE
Dependency for ipex not included in the requirements

### ISSUE THREAD

**Issue by koshyviv** [intel/intel-extension-for-transformers#72]
After following the step by step process, for prerequirsites here
https://github.com/intel/intel-extension-for-transformers/blob/main/examples/huggingface/pytorch/language-modeling/quantization/README.md

And executing the command for Quantization for MPT-7B-chat
```
# "--sq" is used to enable smooth quant
# "--int8_bf16_mixed" is used to enable int8-bf16 mixed mode for platform that natively supports bf16
python run_clm_no_trainer.py \
    --model mosaicml/mpt-7b-chat \
    --revision c8d4750ac8421303665d6ecc253950c69b56d324 \
    --quantize \
    --sq \
    --alpha 0.85 \
    --ipex \
    --output_dir "saved_results"
```

This has a dependency on ipex, but its not included in the parent `requirements.txt` or the  `examples/huggingface/pytorch/language-modeling/quantization/requirements.txt` path

This leads to this error while excuting the above command
```
Traceback (most recent call last):
  File "/home/devcloud/itrex/examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py", line 53, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
```

**Comment by kevinintel** [comment]
Thanks for reminding, koshyviv

**Comment by changwangss** [comment]
Hi, @koshyviv We have an args to distinguish whether to use `--ipex`, please install intel_extension_for_pytorch if use it. we will add a prompt to install.
