### ISSUE TITLE
how to enable AMX in LLM.runtime?

### ISSUE THREAD

**Issue by zhangnju** [intel/intel-extension-for-transformers#721]
HI 

AMX seems to be very valuable to accelerate matrix multiplication in AI workloads. could you help share how to enable AMX in LLM.runtime? only enable NE_AMX in cmake step? do we need others to configure on Intel Sapphire_Rapids platform? 

Thanks

**Comment by zhangnju** [comment]
https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h#L502C26-L502C26 
AMX and AVX512 features would be detected and configured automatically?  is it right?

**Comment by airMeng** [comment]
Hi zhangnju, yes you are right, AMX is enabled if available, you can check related logging as
https://github.com/intel/intel-extension-for-transformers/blob/adb109bad9d4fd83586989991543f5cc2b655b9e/intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h#L535

**Comment by zhangnju** [comment]
Thanks for your confirmation!
