### ISSUE TITLE
What does sparsity ratio mean in this work?

### ISSUE THREAD

**Issue by dataplayer12** [intel/intel-extension-for-transformers#76]
In NVIDIA's version of 2x2 structures sparsity, exactly 2 non-zero values are allowed giving a sparsity ratio of exactly 50%. A few questions about sparsity ratio in this work:
1. Can different 4x1 blocks have different levels of sparsity (i.e. from 25% to 100%)? If so, this is more flexible than NVIDIA's hardware based structured sparsity. Is my understanding correct?
2. Does a sparsity ratio of 80% mean the average sparsity of 4x1 blocks averaged over a layer? Confusion arises because a single 4x1 block can only have a few discrete number of sparsity ratios (0, 25, 50, 75 and 100%)

**Comment by YIYANGCAI** [comment]
Thanks for your question.

In fact, our supported pruning patterns include two typical types:

- **N:M (also known as N in M). which fits NV's hardware**. In this pruning pattern, we prune N elements in a continuous M elements across a weight matrix. For example, for an 2:4 pattern, we prune 2 elements in an 1x4 (or 4x1) structured block. Therefore, the sparsity ratio under this circumstance is exact 50%.
- **NxM, which might not be mentioned in your comments but has already supported and fits Intel's hardwares well.** In this pattern, weights are grouped into NxM blocks, and all weights in the same block are pruned. Therefore, we should set a sparsity ratio to decide how many blocks should be pruned. For instance, for a weight matrix of 32x32, when a 4x1 pattern are applied, we will get totally (32x32) / (4x1) =256 blocks. As your comments mentioned, a sparsity of 80% under this circumstance means that we will prune 256 * 80% ~ 205 blocks of weights. Plus, NxM pattern's block-wise sparsity ratio equals to element-wise sparsity ratio.

BTW, more details for pruning pattern are available in [INC's pruning API](https://github.com/intel/neural-compressor/tree/master/neural_compressor/compression/pruner). INC is another our well-developed tool for model compression and I recommend you to refer it and have a try!

**Comment by dataplayer12** [comment]
@YIYANGCAI Thanks for the comprehensive answer. That answers my question really well..
