### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by ei-grad** [intel/intel-extension-for-transformers#762]
```
Python 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.17.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from transformers import AutoTokenizer, TextStreamer
   ...: from intel_extension_for_transformers.transformers import AutoModelForCausalLM
   ...: 
   ...: model_name = "Intel/neural-chat-7b-v1-1"     # Hugging Face model_id or local 
   ...: model
   ...: prompt = "Once upon a time, there existed a little girl,"
   ...: 
   ...: tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
   ...: inputs = tokenizer(prompt, return_tensors="pt").input_ids
   ...: streamer = TextStreamer(tokenizer)
   ...: 
   ...: model = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True)
   ...: outputs = model.generate(inputs, streamer=streamer, max_new_tokens=300)
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[1], line 2
      1 from transformers import AutoTokenizer, TextStreamer
----> 2 from intel_extension_for_transformers.transformers import AutoModelForCausalLM
      3 model_name = "Intel/neural-chat-7b-v1-1"     # Hugging Face model_id or local model
      4 prompt = "Once upon a time, there existed a little girl,"

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/intel_extension_for_transformers/transformers/__init__.py:19
      1 #!/usr/bin/env python
      2 # -*- coding: utf-8 -*-
      3 #
   (...)
     15 # See the License for the specific language governing permissions and
     16 # limitations under the License.
---> 19 from .config import (
     20     WEIGHTS_NAME,
     21     AutoDistillationConfig,
     22     BenchmarkConfig,
     23     DistillationConfig,
     24     DynamicLengthConfig,
     25     FlashDistillationConfig,
     26     NASConfig,
     27     Provider,
     28     PrunerV2,
     29     PruningConfig,
     30     QuantizationConfig,
     31     TFDistillationConfig,
     32 )
     33 from .distillation import (
     34     SUPPORTED_DISTILLATION_CRITERION_MODE,
     35     DistillationCriterionMode,
     36 )
     37 from .mixture.auto_distillation import AutoDistillation

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/intel_extension_for_transformers/transformers/config.py:22
     20 import yaml
     21 from enum import Enum
---> 22 from neural_compressor.conf.config import (
     23     Distillation_Conf, Pruner, Pruning_Conf, Quantization_Conf
     24 )
     25 from neural_compressor.conf.dotdict import DotDict, deep_set
     26 from .utils.metrics import Metric

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/__init__.py:28
     20 # we need to set a global 'NA' backend, or Model can't be used
     21 from .config import (
     22     DistillationConfig,
     23     PostTrainingQuantConfig,
   (...)
     26     MixedPrecisionConfig,
     27 )
---> 28 from .contrib import *
     29 from .model import *
     30 from .metric import *

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/contrib/__init__.py:18
      1 #!/usr/bin/env python
      2 # -*- coding: utf-8 -*-
      3 #
   (...)
     15 # See the License for the specific language governing permissions and
     16 # limitations under the License.
     17 """Built-in strategy for multiple framework backends."""
---> 18 from .strategy import *

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/contrib/strategy/__init__.py:25
     23 for f in modules:
     24     if isfile(f) and not f.startswith("__") and not f.endswith("__init__.py"):
---> 25         __import__(basename(f)[:-3], globals(), locals(), level=1)

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/contrib/strategy/tpe.py:26
     22 from pathlib import Path
     24 import numpy as np
---> 26 from neural_compressor.strategy.strategy import TuneStrategy, strategy_registry
     27 from neural_compressor.strategy.utils.tuning_sampler import OpWiseTuningSampler
     28 from neural_compressor.strategy.utils.tuning_structs import OpTuningConfig

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/strategy/__init__.py:19
      1 #!/usr/bin/env python
      2 # -*- coding: utf-8 -*-
      3 #
   (...)
     15 # See the License for the specific language governing permissions and
     16 # limitations under the License.
     17 """Intel Neural Compressor Strategy."""
---> 19 from .strategy import STRATEGIES
     20 from os.path import dirname, basename, isfile, join
     21 import glob

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/strategy/strategy.py:35
     32 import numpy as np
     33 import yaml
---> 35 from neural_compressor.adaptor.tensorflow import TensorFlowAdaptor
     37 from ..adaptor import FRAMEWORKS
     38 from ..algorithm import ALGORITHMS, AlgorithmScheduler

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/adaptor/__init__.py:26
     24 for f in modules:
     25     if isfile(f) and not f.startswith("__") and not f.endswith("__init__.py"):
---> 26         __import__(basename(f)[:-3], globals(), locals(), level=1)
     28 __all__ = ["FRAMEWORKS"]

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/adaptor/pytorch.py:43
     40 torch_utils = LazyImport("neural_compressor.adaptor.torch_utils")
     41 ipex = LazyImport("intel_extension_for_pytorch")
---> 43 REDUCE_RANGE = False if CpuInfo().vnni else True
     44 logger.debug("Reduce range is {}".format(str(REDUCE_RANGE)))
     47 def get_torch_version():

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/utils/utility.py:129, in singleton.<locals>._singleton(*args, **kw)
    127 """Create a singleton object."""
    128 if cls not in instances:
--> 129     instances[cls] = cls(*args, **kw)
    130 return instances[cls]

File ~/.virtualenvs/intel-transformers/lib/python3.10/site-packages/neural_compressor/utils/utility.py:254, in CpuInfo.__init__(self)
    252 self._sockets = self.get_number_of_sockets()
    253 self._cores = psutil.cpu_count(logical=False)
--> 254 self._cores_per_socket = int(self._cores / self._sockets)

ZeroDivisionError: division by zero
```

**Comment by Zhenzhong1** [comment]
Hi, the error you met, I thought it was the neural compressor issue recently.
https://github.com/intel/neural-compressor/blob/master/neural_compressor/utils/utility.py#L255C34-L255C55
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/a95a0617-539c-409a-819f-8e6a19edcafa)

Please install the ITREX from the source code~
I have run the whole installation process. It's ok if you follow the commands.

```
git clone https://github.com/intel/intel-extension-for-transformers
cd intel-extension-for-transformers
pip install -r requirements.txt
pip install transformers==4.33.1
python setup.py install
```

Please put your script **outside of the intel-extension-for-transformers root directory** to make sure the script calls API from the conda env you installed rather than local ITREX directories.
```python
from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM
model_name = "Intel/neural-chat-7b-v1-1"     # Hugging Face model_id or local model
prompt = "Once upon a time, there existed a little girl,"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
inputs = tokenizer(prompt, return_tensors="pt").input_ids
streamer = TextStreamer(tokenizer)

model = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True)
outputs = model.generate(inputs, streamer=streamer, max_new_tokens=300)
```
Inference screenshot:
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/8c135c7a-6580-4ab7-a691-71837815c265)

**Comment by KangkangStu** [comment]
Traceback (most recent call last):
  File "/home/kangyuhan/finetuning/intel-transformers/intel-extension-for-transformers/demo.py", line 2, in <module>
    from intel_extension_for_transformers.transformers import AutoModelForCausalLM
  File "/home/kangyuhan/finetuning/intel-transformers/intel-extension-for-transformers/intel_extension_for_transformers/transformers/__init__.py", line 19, in <module>
    from .config import (
  File "/home/kangyuhan/finetuning/intel-transformers/intel-extension-for-transformers/intel_extension_for_transformers/transformers/config.py", line 22, in <module>
    from neural_compressor.conf.config import (
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/__init__.py", line 28, in <module>
    from .contrib import *
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/contrib/__init__.py", line 18, in <module>
    from .strategy import *
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/contrib/strategy/__init__.py", line 25, in <module>
    __import__(basename(f)[:-3], globals(), locals(), level=1)
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/contrib/strategy/sigopt.py", line 21, in <module>
    from neural_compressor.strategy.strategy import TuneStrategy, strategy_registry
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/strategy/__init__.py", line 19, in <module>
    from .strategy import STRATEGIES
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/strategy/strategy.py", line 35, in <module>
    from neural_compressor.adaptor.tensorflow import TensorFlowAdaptor
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/adaptor/__init__.py", line 26, in <module>
    __import__(basename(f)[:-3], globals(), locals(), level=1)
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/adaptor/pytorch.py", line 43, in <module>
    REDUCE_RANGE = False if CpuInfo().vnni else True
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/utils/utility.py", line 129, in _singleton
    instances[cls] = cls(*args, **kw)
  File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/utils/utility.py", line 257, in __init__
    self._cores_per_socket = int(self._cores / self._sockets)
ZeroDivisionError: division by zero 

I encountered the same problem. My cpu is  Intel Xeon Platinum 8358

**Comment by KangkangStu** [comment]
回溯（最近一次调用最后一次）：
文件“/home/kangyuhan/finetuning/intel-transformers/intel-extension-for-transformers/demo.py”，第 2 行，来自
intel_extension_for_transformers.transformers import AutoModelForCausalLM
文件“/home/kangyuhan /finetuning/intel-transformers/intel-extension-for-transformers/intel_extension_for_transformers/transformers/ init .py"，第 19 行，来自
.config import (
文件 "/home/kangyuhan/finetuning/intel-transformers/intel-extension- for-transformers/intel_extension_for_transformers/transformers/config.py"，第 22 行，来自
neural_compressor.conf.config import (
File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor / init .py”，第 28 行，来自
.contrib import *
文件“/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/contrib/ init .py”，第 18 行，在
from .strategy import *
文件“/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/contrib/strategy/ init .py”，第 25 行，在
import (basename( f)[:-3], globals(), locals(), level=1)
文件“/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/contrib/strategy/ sigopt.py”，第 21 行，来自
neural_compressor.strategy.strategy导入TuneStrategy，strategy_registry
文件“/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/strategy/ init .py ”，第 19 行，来自
.strategy import STRATEGIES
文件“/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/strategy/strategy.py”，第 35 行，来自
neural_compressor .adaptor.tensorflow import TensorFlowAdaptor
文件“/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/adaptor/ init .py”，第 26 行，导入
( basename(f)[ :-3], globals(), locals(), level=1)
文件 "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/adaptor/pytorch.py​​",第 43 行，在
REDUCE_RANGE = False if CpuInfo().vnni else True
File "/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/utils/utility.py"，第 129 行，在 _singleton
实例中[cls] = cls(*args, **kw)
文件“/home/kangyuhan/.conda/envs/llama_factory/lib/python3.10/site-packages/neural_compressor/utils/utility.py”，第 257 行，在init
self._cores_per_socket = int(self._cores / self._sockets)
ZeroDivisionError：除以零

我遇到了同样的问题。我的CPU是Intel Xeon Platinum 8358 操作系统为Linux
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
座：                 2
NUMA 节点：         2
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              106
型号名称：        Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
步进：              6
CPU MHz：             800.000
CPU max MHz:           3400.0000
CPU min MHz:           800.0000
BogoMIPS：            5200.00
虚拟化：           VT-x
L1d 缓存：          48K
L1i 缓存：          32K
L2 缓存：           1280K
L3 缓存：           49152K
NUMA 节点0 CPU：    0-31,64-95
NUMA 节点1 CPU：    32-63,96-127

**Comment by Spycsh** [comment]
@KangkangStu Thanks for detailed information! I believe this is because your system is non-english. I will let you know after fixing this problem.

**Comment by Spycsh** [comment]
@ei-grad , should work after https://github.com/intel/neural-compressor/pull/1514 is merged. Please re-install neural compressor from source (https://github.com/intel/neural-compressor/blob/master/docs/source/installation_guide.md#install-from-source) and check. Let me know if you have any further problems!
