### ISSUE TITLE
Cant even install this thing - error during pip installation

### ISSUE THREAD

**Issue by PedzacyKapec** [intel/intel-extension-for-transformers#770]
When pip installing this is what i get:

Collecting intel-extension-for-transformers
  Using cached intel-extension-for-transformers-1.2.1.tar.gz (88.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>  
        File "C:\Users\WORKSTATION\AppData\Local\Temp\pip-install-wycighm3\intel-extension-for-transformers_ce809ed1ec2d4a63834d87068def41c5\setup.py", line 27, in <module>
          from cpuinfo import get_cpu_info
      ModuleNotFoundError: No module named 'cpuinfo'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.        
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Dizro** [comment]
Could you try `pip install py-cpuinfo` and check if `pip install -U tables` works after that?

**Comment by PedzacyKapec** [comment]
> Could you try `pip install py-cpuinfo`

Yes both installed succesfully.
Then when i tried to install it again i got an error again:
    [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for intel-extension-for-transformers
  Running setup.py clean for intel-extension-for-transformers 
Failed to build intel-extension-for-transformers
ERROR: Could not build wheels for intel-extension-for-transformers, which is required to install pyproject.toml-based projects

**Comment by XiaoyongW** [comment]
> > Could you try `pip install py-cpuinfo`
> 
> Yes. Installed succesfully. Then when i tried to install it again i got an error again: [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for intel-extension-for-transformers Running setup.py clean for intel-extension-for-transformers Failed to build intel-extension-for-transformers ERROR: Could not build wheels for intel-extension-for-transformers, which is required to install pyproject.toml-based projects

I guess you are using Windows 10 or higher to download. I also got this error. Updating the pip\wheel\setuptools tool has no effect. I switched the system to Ubuntu 20.04 and this problem was solved. Or you can try to install WSL2 on Windows to solve the problem.

**Comment by kevinintel** [comment]
Hi, I will close this issue if you don't have concerns
