### ISSUE TITLE
Use the quantized int4 Qwen-chat model to generate the wrong output

### ISSUE THREAD

**Issue by zhengshuo1** [intel/intel-extension-for-transformers#803]
I used the scripts/quantize to quantize the Qwen-chat model. The input is about 910-length tokens. The output is not proper.
The output is shown as below.
<|im_start|>'t be able to summarize the meeting.<|im_end|>
<|endoftext|> [end of text]
When I used the same input for qwen.cpp, the output is proper, just like "1. Topic: Software-defined peripheral and its development......"
I wonder what the problem is.

**Comment by intellinjun** [comment]
@zhengshuo1 Can you provide more details, such as the code and prompt used, so I can reproduce your situation? It would be better if there were screenshots.

**Comment by zhengshuo1** [comment]
The first screenshot is the output of IRTEX ("fill done" is my added log, ignore it. )
The second screeshot is the output of qwen.cpp.
My prompt is in 2_1.txt.
Maybe you would reproduce it using the 2_1.txt
<img width="1267" alt="屏幕截图 2023-11-29 142355" src="https://github.com/intel/intel-extension-for-transformers/assets/41314866/65dbb1eb-d418-4068-b55d-fb6a28625798">
<img width="851" alt="屏幕截图 2023-11-29 142927" src="https://github.com/intel/intel-extension-for-transformers/assets/41314866/98f91c19-1fd7-4905-913d-92f5d283bc4e">
[2_1.txt](https://github.com/intel/intel-extension-for-transformers/files/13496883/2_1.txt)

**Comment by zhengshuo1** [comment]
> @zhengshuo1 Can you provide more details, such as the code and prompt used, so I can reproduce your situation? It would be better if there were screenshots.

Hello, please check my response.

**Comment by intellinjun** [comment]
This uses qwen's chat mode, and you can add specific prompts before and after the prompt according to this PR
https://github.com/intel/intel-extension-for-transformers/pull/808

**Comment by intellinjun** [comment]
here is result 
![image](https://github.com/intel/intel-extension-for-transformers/assets/105184542/f778ff36-2c0a-4eda-a9c5-870abe32e630)
![image](https://github.com/intel/intel-extension-for-transformers/assets/105184542/b64b3cab-4d2c-4b54-a245-a20c0abbfdd5)

**Comment by intellinjun** [comment]
@zhengshuo1

**Comment by zhengshuo1** [comment]
> I recommend you to use our Python API for more convenience
> 
> ```python
> from transformers import AutoTokenizer, TextStreamer
> from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig
> model_name = "/mnt/disk1/data2/linjun/model/Qwen-7B-Chat/"     # Hugging Face model_id or local model
> woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4",use_cache=True)
> prompt = '''\n<|im_start|>user\nSummarize the meeting. The meeting content is:
> A:Thank you two bosses, then ah, that me, first introduce some of the work we did before, that about this uh software-defined peripheral to this uh bosses, and then let's open the discussion later to see what kind of cooperation opportunities there are, okay. 
> A:OK, well, then my side, uh, first tell you about the work we do, wait a minute. 
> A:can you see that? 
> Paul Luo :ok. 
> A:Well, okay, this, uh, our side, uh, is this notebook research and development platform, the team is under Lao Mo, and then this past few years, we have actually been doing some work in this uh platform software or the direction of the underlying software, well, at present, we are focusing the work of this platform software on a uh, we define the direction of software-defined peripherals, uh, the so-called software-defined peripherals. 
> A:What is a software-defined peripheral? 
> A:In what we know, now this our peripheral, uh, in fact, uh, frankly speaking, especially notebook peripherals, in fact, this is highly homogeneous, this includes this, uh camera hard disk, including this graphics card sound card, in fact, this manufacturer is actually similar, so how to find some of the differentiation of our products, may be more from that situation may have to start from that software, then how to start from the software how to do it? 
> A:filter driver, plus background services, then through these several of this uh, software components, we can extend the capabilities of this uh peripheral, for example, we go to some value-added functions, such as some special effects of AI. 
> A:This example is in our camera, this we this uh uh uh has an LLC software, through this uh, AI algorithms, including beauty, including background bokeh, background replacement, etc., these algorithms are integrated into one of our filters driver, in this way, this adds a function of this beauty effect to our uh Lenovo product. 
> A:Let's say this, uh, in this direction of showing us. 
> A:Through a virtual graphics card drama, we can effectively integrate our original, such as dual-screen products, into a flat. 
> A:In addition, we can also effectively share our uh desktop with other devices through this multi-screen extension technology, including this PC, including Android devices, and even this, uh iOS, or microphone OS devices. 
> A:So through our uh, the so-called software-defined peripherals, this way can effectively expand the capabilities and performance of our this, uh, peripherals of the product. 
> A:At the same time, we can do some fusion, for example, we can put this. 
> A:Well, the sound and our camera capabilities are fused together to make some of this voice, this privacy function, such as what we are doing now with this SB uh segment, you can fuse this uh multiple capabilities, including this audio, including this uh camera together to achieve this intelligent this. 
> A:This multiple features of this AI. 
> A:This right, you can also see ah, this is a framework diagram of our overall software-defined peripheral, a few years ago, we called it this virtual device framework, these two years, we called it this software-defined peripheral, well, in fact, the overall framework is the bottom is our hardware, above this, is the driver of this physical device of our hardware, which is generally implemented by Microsoft, on the Internet is our framework, our framework currently includes this camera。 
> A:Audio and display and so on in a few main directions. Through this virtual device driver, through this filter, through some background services, and so on, these software methods extend the capabilities of this primitive peripheral. On the Internet, we provide this upper-layer application through this uh runtime API of Windows, so that our upper-layer application actually has a lot of AI, or even VR AR and other functions.
> A:Behind me in this uh, a little bit more detail about these directions. 
> A:This diagram is the overall architecture of our current uh, virtual camera, which is currently applied in this wisdom. 
> A:We are developing this SB segment wisdom and this consumer LIC two software you can see ah, this overall architecture is still uh, more complicated. 
> A:He's now a fusion of this, uh, two, uh, this virtual technology, yes, uh, so-called this.<|im_end|>\n<|im_start|>assistant\n
> '''
> 
> tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
> inputs = tokenizer(prompt, return_tensors="pt").input_ids
> streamer = TextStreamer(tokenizer)
> 
> model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config)
> 
> # Paper: https://arxiv.org/pdf/2309.17453.pdf
> # Recommend n_keep=4 to do attention sinks (four initial tokens) and n_discard=-1 to drop half rencetly tokens when meet length threshold
> outputs = model.generate(inputs, streamer=streamer, max_new_tokens=300, ctx_size=2048, n_keep=4, n_discard=-1, do_sample=False)
> ```

Thank you.  Maybe you could close this issue.

**Comment by intellinjun** [comment]
> > I recommend you to use our Python API for more convenience
> > ```python
> > from transformers import AutoTokenizer, TextStreamer
> > from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig
> > model_name = "/mnt/disk1/data2/linjun/model/Qwen-7B-Chat/"     # Hugging Face model_id or local model
> > woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4",use_cache=True)
> > prompt = '''\n<|im_start|>user\nSummarize the meeting. The meeting content is:
> > A:Thank you two bosses, then ah, that me, first introduce some of the work we did before, that about this uh software-defined peripheral to this uh bosses, and then let's open the discussion later to see what kind of cooperation opportunities there are, okay. 
> > A:OK, well, then my side, uh, first tell you about the work we do, wait a minute. 
> > A:can you see that? 
> > Paul Luo :ok. 
> > A:Well, okay, this, uh, our side, uh, is this notebook research and development platform, the team is under Lao Mo, and then this past few years, we have actually been doing some work in this uh platform software or the direction of the underlying software, well, at present, we are focusing the work of this platform software on a uh, we define the direction of software-defined peripherals, uh, the so-called software-defined peripherals. 
> > A:What is a software-defined peripheral? 
> > A:In what we know, now this our peripheral, uh, in fact, uh, frankly speaking, especially notebook peripherals, in fact, this is highly homogeneous, this includes this, uh camera hard disk, including this graphics card sound card, in fact, this manufacturer is actually similar, so how to find some of the differentiation of our products, may be more from that situation may have to start from that software, then how to start from the software how to do it? 
> > A:filter driver, plus background services, then through these several of this uh, software components, we can extend the capabilities of this uh peripheral, for example, we go to some value-added functions, such as some special effects of AI. 
> > A:This example is in our camera, this we this uh uh uh has an LLC software, through this uh, AI algorithms, including beauty, including background bokeh, background replacement, etc., these algorithms are integrated into one of our filters driver, in this way, this adds a function of this beauty effect to our uh Lenovo product. 
> > A:Let's say this, uh, in this direction of showing us. 
> > A:Through a virtual graphics card drama, we can effectively integrate our original, such as dual-screen products, into a flat. 
> > A:In addition, we can also effectively share our uh desktop with other devices through this multi-screen extension technology, including this PC, including Android devices, and even this, uh iOS, or microphone OS devices. 
> > A:So through our uh, the so-called software-defined peripherals, this way can effectively expand the capabilities and performance of our this, uh, peripherals of the product. 
> > A:At the same time, we can do some fusion, for example, we can put this. 
> > A:Well, the sound and our camera capabilities are fused together to make some of this voice, this privacy function, such as what we are doing now with this SB uh segment, you can fuse this uh multiple capabilities, including this audio, including this uh camera together to achieve this intelligent this. 
> > A:This multiple features of this AI. 
> > A:This right, you can also see ah, this is a framework diagram of our overall software-defined peripheral, a few years ago, we called it this virtual device framework, these two years, we called it this software-defined peripheral, well, in fact, the overall framework is the bottom is our hardware, above this, is the driver of this physical device of our hardware, which is generally implemented by Microsoft, on the Internet is our framework, our framework currently includes this camera。 
> > A:Audio and display and so on in a few main directions. Through this virtual device driver, through this filter, through some background services, and so on, these software methods extend the capabilities of this primitive peripheral. On the Internet, we provide this upper-layer application through this uh runtime API of Windows, so that our upper-layer application actually has a lot of AI, or even VR AR and other functions.
> > A:Behind me in this uh, a little bit more detail about these directions. 
> > A:This diagram is the overall architecture of our current uh, virtual camera, which is currently applied in this wisdom. 
> > A:We are developing this SB segment wisdom and this consumer LIC two software you can see ah, this overall architecture is still uh, more complicated. 
> > A:He's now a fusion of this, uh, two, uh, this virtual technology, yes, uh, so-called this.<|im_end|>\n<|im_start|>assistant\n
> > '''
> > 
> > tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
> > inputs = tokenizer(prompt, return_tensors="pt").input_ids
> > streamer = TextStreamer(tokenizer)
> > 
> > model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config)
> > 
> > # Paper: https://arxiv.org/pdf/2309.17453.pdf
> > # Recommend n_keep=4 to do attention sinks (four initial tokens) and n_discard=-1 to drop half rencetly tokens when meet length threshold
> > outputs = model.generate(inputs, streamer=streamer, max_new_tokens=300, ctx_size=2048, n_keep=4, n_discard=-1, do_sample=False)
> > ```
> 
> Thank you. Maybe you could close this issue.

OK
