### ISSUE TITLE
File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/utils/store.py" ; data = store.get(f"{prefix}{idx}") RuntimeError: Socket Timeout

### ISSUE THREAD

**Issue by Abhaycnvrg** [intel/intel-extension-for-transformers#84]
File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/utils/store.py", line 34, in get_all
data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout
PyTorch command failed on worker #vbsbi
PyTorch command failed on worker #5xzl9
An error has caused the experiment to fail

Running this script https://github.com/intel/intel-extension-for-transformers/tree/main/workflows/chatbot/fine_tuning
python finetune_clm.py \
        --model_name_or_path "mosaicml/mpt-7b" \
        --bf16 True \
        --train_file "/path/to/alpaca_data.json" \
        --dataset_concatenation \
        --per_device_train_batch_size 2 \
        --per_device_eval_batch_size 2 \
        --gradient_accumulation_steps 4 \
        --evaluation_strategy "no" \
        --save_strategy "steps" \
        --save_steps 2000 \
        --save_total_limit 1 \
        --learning_rate 1e-4  \
        --logging_steps 1 \
        --do_train \
        --num_train_epochs 3 \
        --overwrite_output_dir \
        --log_level info \
        --output_dir ./mpt_peft_finetuned_model \
        --peft lora \
        --trust_remote_code True \
        --tokenizer_name "EleutherAI/gpt-neox-20b" \
        --habana \
        --use_habana \
        --use_lazy_mode \

**Comment by lvliang-intel** [comment]
@Abhaycnvrg,
Did you run the finetuning on Habana Gaudi? Could you please share the detailed steps and complete log trace of the finetuning process？ Thanks.

**Comment by kevinintel** [comment]
Hi @Abhaycnvrg ,
I will close this issue if you don't have concerns.
