### ISSUE TITLE
[question]convert qwen failed

### ISSUE THREAD

**Issue by kunger97** [intel/intel-extension-for-transformers#845]
I'm trying to use LLMRuntime to run the qwen model (a fine-tuned model, not the official one). When I execute `python script/run.py <ModelPath>`, Python throws an exception:

```
Traceback (most recent call last):
  File "/home/*/LLMs/intel-extension-for-transformers/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_qwen.py", line 177, in <module>
    main()
  File "/home/*/LLMs/intel-extension-for-transformers/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_qwen.py", line 142, in main
    data = list_vars[src].squeeze().numpy()
TypeError: Got unsupported ScalarType BFloat16
```

I can't find any info in the doc, Is there anything I may missing? please help me resolve this issue.

**Comment by a32543254** [comment]
"_name_or_path": "Qwen/Qwen-14B-Chat",
  "architectures": [
    "QWenLMHeadModel"
  ],
  "attn_dropout_prob": 0.0,
  "auto_map": {
    "AutoConfig": "Qwen/Qwen-14B-Chat--configuration_qwen.QWenConfig",
    "AutoModelForCausalLM": "Qwen/Qwen-14B-Chat--modeling_qwen.QWenLMHeadModel"
  },
  **"bf16": true,**

I see, above is the config.py from your finetune model.
Your fine-tuned version model is Bf16 version which result to this error.

If you are in a hurry. You can convert this model to fp32 first, then load by our API.
OR You can wait for us to support this bf16 dtype model.

BTW, I will let you know as long as we support it.

Reagrds,
Bo

**Comment by kunger97** [comment]
Thank you for your response. I'm glad to learn that you have plans to support BF16. Regarding the model conversion you mentioned earlier, could you please clarify if there are corresponding tools in LLM Runtime for this purpose, or if I need to write my own code for the conversion?

**Comment by intellinjun** [comment]
> Thank you for your response. I'm glad to learn that you have plans to support BF16. Regarding the model conversion you mentioned earlier, could you please clarify if there are corresponding tools in LLM Runtime for this purpose, or if I need to write my own code for the conversion?

You could reference this [issue](https://github.com/pytorch/pytorch/issues/109873) in pytorch for unsupport bf16

**Comment by a32543254** [comment]
If there are no more issues, I will close it.
