### ISSUE TITLE
My process is killed.

### ISSUE THREAD

**Issue by XiaoyongW** [intel/intel-extension-for-transformers#846]
When I try to use this demo:
`from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM
model_name = "/mnt/e/Programming/CPULLM/model/neuChat"     # Hugging Face model_id or local model
prompt = "Once upon a time, there existed a little girl,"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True, repo_type="Local")
inputs = tokenizer(prompt, return_tensors="pt").input_ids
streamer = TextStreamer(tokenizer)

model = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True)
outputs = model.generate(inputs, streamer=streamer, max_new_tokens=300)
print(outputs)`

The logs I get are as follows:
`Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2023-12-03 15:01:30 [INFO] CPU device is used.
Killed`
Why is this happening?

**Comment by hshen14** [comment]
Thanks for reporting the issue. Could you please share your machine info? You may paste the output of "lscpu" if your env is linux.

**Comment by XiaoyongW** [comment]
> Thanks for reporting the issue. Could you please share your machine info? You may paste the output of "lscpu" if your env is linux.

I have solved this problem. The reason was that the CPU memory was too small and triggered the OOM Killer mechanism. I solved this problem by increasing the virtual memory by adding swap partitions. Thanks for your attention!

**Comment by a32543254** [comment]
You're welcome, thanks for your usage.
