### ISSUE TITLE
Not working for Vicuna 1.5

### ISSUE THREAD

**Issue by tonyliangli** [intel/intel-extension-for-transformers#881]
Vicuna 1.5 should be a LLama-2 series model, but it's not working.  The \<unk> token is decoded like "\<s> Once upon a time, there existed a little girl,\<unk>", and the generation process stops. What could be the problem?

**Comment by a32543254** [comment]
> I tested Baichuan and it doesn't work either. The. 1.3.0.dev version from the docker image works fine for vicuna. I think this problem is related to the latest 1.2.2 version?

Yes, please use newest version for test.
For vicuna please use  1.3.0.dev version 
For Baichuan, you can see from DOC, we only baichuan 14B for now, which means Baichuan 7B and others is not support for now.
 could you kindly check whether you are using a correct version of Baichuan ?

**Comment by tonyliangli** [comment]
> > I tested Baichuan and it doesn't work either. The. 1.3.0.dev version from the docker image works fine for vicuna. I think this problem is related to the latest 1.2.2 version?
> 
> Yes, please use newest version for test. For vicuna please use 1.3.0.dev version For Baichuan, you can see from DOC, we only baichuan 14B for now, which means Baichuan 7B and others is not support for now. could you kindly check whether you are using a correct version of Baichuan ?

I'm using Baichuan2-13B-Chat. The 1.3.0.dev also has bugs, e.g. the cache is not automatically loaded so every time I run with transformers, the convert and quant process will go through again.

**Comment by a32543254** [comment]
Sorry for that.
Are you using following link ? 
https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat
And could you provide some log for us?
what the error ?

**Comment by tonyliangli** [comment]
> Got it, what dtype you are using now? Could you try quant to in4 then do inference? And if you are using fp32 dtype please try this [PR](https://github.com/intel/intel-extension-for-transformers/pull/832/files#diff-e358e23e7db403fce7607a44951ed91361a22c8589dd7348e562f0b27592293eL257), we plan to fix a bug recently, but not merge yet.

I tried int4 and int8, none of those worked. They work fine in the 1.2.1 version.

**Comment by a32543254** [comment]
Let me make it clear 
Vicuna int4 is working fine in 1.3.0.dev but not 1.2.1  
Baichuan2-13B-Chat both int4 and int8 is working fine  1.2.1  but not 1.3.0 dev ?   
and the issue is output is <unk> . 
What cpu you are using now?
Could you try newest version which is build from source ?
