### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by kithogue** [intel/intel-extension-for-transformers#893]
The version is relying on transformers 4.34 dependency at the moment, but is requiring transformers 4.35 as per requirement parser. Please fix!

**Comment by VincyZhang** [comment]
Thanks @kithogue , would you mind give us more details about the conflict you found? In some cases we have to constrain transformers to 4.34, but in most cases we didn't have such limitation. What's your use case?

**Comment by kevinintel** [comment]
Hi @kithogue , can you share your use case?

**Comment by kevinintel** [comment]
Close it first until the user provide details
