### ISSUE TITLE
Version conflict when importing AutoModelForCausalLM from intel_extension_for_transformers.transformers.modeling

### ISSUE THREAD

**Issue by benjamin-marie** [intel/intel-extension-for-transformers#918]
When I run:
`from intel_extension_for_transformers.transformers.modeling import AutoModelForCausalLM`

It triggers this error:

> ContextualVersionConflict: (transformers 4.35.2 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('transformers==4.34.1'), {'intel-extension-for-transformers'})

It can be reproduced on Google Colab (CPU runtime). I tried to install intel_extension_for_transformers with pip and source but got the same errors with both. I also tried to downgrade transformers to 4.34.1 but the error is still there.

**Comment by PenghuiCheng** [comment]
Hi, @benjamin-marie , what version do you use? I try to reproduce your issue on intel-extension-for-transformers version 1.3.1 and transformers version 4.36.2. It is OK in my side.

thanks!
Cheng, Penghui

**Comment by kevinintel** [comment]
Close issue first until the users give more details
