### ISSUE TITLE
Generating meaningless results

### ISSUE THREAD

**Issue by ailxcds** [intel/intel-extension-for-transformers#929]
Hi! I tried to load the [`FlagAlpha/Llama2-Chinese-7b-Chat`](https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat) model using the llama2 chat sample code, the model is base on meta's `meta-llama/Llama-2-7b-chat-hf` and speed is excellent, but it generated meaningless results. Is it related to model support or did I overlook something?

```python
from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig

# Please change to local path to model, llama2 does not support online conversion, currently.
model_name = "FlagAlpha/Llama2-Chinese-7b-Chat"
woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4")
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
streamer = TextStreamer(tokenizer)
model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, trust_remote_code=True)

while True:
    prompt = input("> ").strip()
    if prompt == "quit":
        break
    b_prompt = "[INST]{}[/INST]".format(prompt)  # prompt template for llama2
    inputs = tokenizer(b_prompt, return_tensors="pt").input_ids
    outputs = model.generate(inputs, streamer=streamer, interactive=True, ignore_prompt=True, do_sample=True)
```
version:
```
intel-extension-for-transformers 1.2.2
transformers                     4.34.1
transformers-stream-generator    0.0.4
```

![image](https://github.com/intel/intel-extension-for-transformers/assets/18321971/3b64135b-0cad-45b8-bac8-f98899a36eae)
![image](https://github.com/intel/intel-extension-for-transformers/assets/18321971/af7a7426-2c81-4f6f-b38f-bc4a69079892)

Thanks!

**Comment by a32543254** [comment]
Thanks for you usage,
1. Could try newest branch and build from source  rather than 1.2.2 ?
2. And I would recommend you replace 
while True:
    prompt = input("> ").strip()
    if prompt == "quit":
        break
    b_prompt = "[INST]{}[/INST]".format(prompt)  # prompt template for llama2
    inputs = tokenizer(b_prompt, return_tensors="pt").input_ids
    outputs = model.generate(inputs, streamer=streamer, interactive=True, ignore_prompt=True, do_sample=True)
    
 To
prompt = "once upon a time, there is a girl"
inputs = tokenizer(prompt, return_tensors="pt").input_ids
outputs = model.generate(inputs, streamer=streamer, interactive=True, ignore_prompt=True, do_sample=True)

Because this template is mainly for llama 2 chat rather for Chinese version model.

**Comment by ailxcds** [comment]
Building from source(1.2.3.dev68+g43e30bcabd) worked fine, thanks

**Comment by a32543254** [comment]
Thanks for your usage!
