### ISSUE TITLE
failed to run model conversion for qwen-7B

### ISSUE THREAD

**Issue by zhangnju** [intel/intel-extension-for-transformers#953]
Hi 
when trying to convert qwen_7b model, I met the below issue:
TypeError: Got unsupported ScalarType BFloat16 

since qwen is supported by llm.runtime, could you please check what's wrong with steps?

Thanks 
 
model conversion command: python scripts/convert.py --outtype f32 --outfile ne-f32.bin /mnt/model/qwen_7b/ 

model source: huggingface Qwen/Qwen-7B 

error log:
Model loaded:  /mnt/model/qwen_7b
{'vocab_size': 151936, 'hidden_size': 4096, 'intermediate_size': 22016, 'num_hidden_layers': 32, 'num_attention_heads': 32, 'emb_dropout_prob': 0.0, 'attn_dropout_prob': 0.0, 'layer_norm_epsilon': 1e-06, 'initializer_range': 0.02, 'scale_attn_weights': True, 'use_cache': True, 'max_position_embeddings': 32768, 'bf16': True, 'fp16': False, 'fp32': False, 'kv_channels': 128, 'rotary_pct': 1.0, 'rotary_emb_base': 10000, 'use_dynamic_ntk': True, 'use_logn_attn': True, 'use_flash_attn': True, 'no_bias': True, 'use_cache_quantization': False, 'use_cache_kernel': False, 'softmax_in_fp32': False, 'return_dict': True, 'output_hidden_states': False, 'output_attentions': False, 'torchscript': False, 'torch_dtype': None, 'use_bfloat16': False, 'tf_legacy_loss': False, 'pruned_heads': {}, 'tie_word_embeddings': False, 'is_encoder_decoder': False, 'is_decoder': False, 'cross_attention_hidden_size': None, 'add_cross_attention': False, 'tie_encoder_decoder': False, 'max_length': 20, 'min_length': 0, 'do_sample': False, 'early_stopping': False, 'num_beams': 1, 'num_beam_groups': 1, 'diversity_penalty': 0.0, 'temperature': 1.0, 'top_k': 50, 'top_p': 1.0, 'typical_p': 1.0, 'repetition_penalty': 1.0, 'length_penalty': 1.0, 'no_repeat_ngram_size': 0, 'encoder_no_repeat_ngram_size': 0, 'bad_words_ids': None, 'num_return_sequences': 1, 'chunk_size_feed_forward': 0, 'output_scores': False, 'return_dict_in_generate': False, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'remove_invalid_values': False, 'exponential_decay_length_penalty': None, 'suppress_tokens': None, 'begin_suppress_tokens': None, 'architectures': ['QWenLMHeadModel'], 'finetuning_task': None, 'id2label': {0: 'LABEL_0', 1: 'LABEL_1'}, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'tokenizer_class': 'QWenTokenizer', 'prefix': None, 'bos_token_id': None, 'pad_token_id': None, 'eos_token_id': None, 'sep_token_id': None, 'decoder_start_token_id': None, 'task_specific_params': None, 'problem_type': None, '_name_or_path': '/mnt/model/qwen_7b', 'transformers_version': '4.36.1', 'auto_map': {'AutoConfig': 'configuration_qwen.QWenConfig', 'AutoModelForCausalLM': 'modeling_qwen.QWenLMHeadModel'}, 'model_type': 'qwen', 'onnx_safe': None, 'seq_length': 8192}
transformer.wte.weight  ->  transformer.wte.weight
Traceback (most recent call last):
  File "/mnt/intel-extension-for-transformers/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_qwen.py", line 177, in <module>
    main()
  File "/mnt/intel-extension-for-transformers/intel_extension_for_transformers/llm/runtime/graph/scripts/convert_qwen.py", line 143, in main
    data = list_vars[src].squeeze().numpy()
TypeError: Got unsupported ScalarType BFloat16

**Comment by a32543254** [comment]
https://huggingface.co/Qwen/Qwen-7B/blob/ffe04dd57f85293043ba999a2c0daa788d6182e9/config.json#L10
You must using a fine tune version of Qwen right? 
because the origin model in Huggingface the BF16 is false.
Please refer to issue here https://github.com/pytorch/pytorch/issues/110285

I recommend you load a bf16: false Qwen model

**Comment by zhangnju** [comment]
Hi @a32543254 I checked the model source, which is origin model https://huggingface.co/Qwen/Qwen-7B/tree/main

**Comment by zhangnju** [comment]
this issue has been fixed by me
