### ISSUE TITLE
Support Mixtral

### ISSUE THREAD

**Issue by bratao** [intel/intel-extension-for-transformers#963]
I would love to use Intel CPU for Mixtral prediction. It is something possible or Fast MoE is intractable on CPU yet?

**Comment by a32543254** [comment]
Yes, we already had plan to support Mixtral soon.
Please stay tune!

**Comment by AdityaKulshrestha** [comment]
Hi, I am trying to use Mixtral. Is there any progress made for the support of Mixtral. If yes, can you provide with quick support or code snippets for getting started. 

Thanks!

**Comment by kevinintel** [comment]
We already support it, please follow the document: https://github.com/intel/intel-extension-for-transformers/tree/main/examples/huggingface/neural_speed and change the model_path
